ig.module
("game.entities.ui.btns.arrow-btn").requires
('impact.entity',"game.entities.ui.btns.button-base").defines(function()
{EntityArrowBtn=EntityButtonBase.extend({collides:ig.Entity.COLLIDES.NEVER,type:ig.Entity.TYPE.NONE,checkAgainst:ig.Entity.TYPE.NONE,size:{x:81,y:80},upImage:new ig.Image("media/images/ui/btns/arrow_btn_up.png"),downImage:new ig.Image("media/images/ui/btns/arrow_btn_down.png"),arrowDirection:"",init:function(x,y,settings)
{this.arrowDirection=settings.arrowDirection;this.parent(x,y,settings);this.offset.x=(81*0.5)-(this.size.x*0.5);this.offset.y=(80*0.5)-(this.size.y*0.5);if(this.arrowDirection==="up")
this.currentImage=this.upImage;if(this.arrowDirection==="down")
this.currentImage=this.downImage;},changeImage:function($value,$playTween)
{switch($value)
{case"up":if(this.arrowDirection==="up")
this.currentImage=this.upImage;if(this.arrowDirection==="down")
this.currentImage=this.downImage;if($playTween===true)
TweenMax.to(this,this.scaleTime,{scaleX:1,scaleY:1,ease:Back.easeOut});break;case"down":if(this.arrowDirection==="up")
this.currentImage=this.upImage;if(this.arrowDirection==="down")
this.currentImage=this.downImage;if($playTween===true)
TweenMax.to(this,this.scaleTime,{scaleX:this.scaledX,scaleY:this.scaledY,ease:Back.easeOut});break;}},onPressed:function()
{this.parent();this.changeImage("down",true);if(this.arrowDirection==="up")
ig.game.handleEvent("upArrowBtnClicked");if(this.arrowDirection==="down")
ig.game.handleEvent("downArrowBtnClicked");},onMouseOver:function()
{this.changeImage("down",true);},onMouseOut:function()
{this.changeImage("up",true);},update:function()
{this.parent();if(this.isScaledDown&&this.focused===false)
{this.changeImage("up",true);this.isScaledDown=false;}},draw:function()
{this.parent();var ctx=ig.system.context;ctx.save();var iWidthHalf=(this.size.x*0.5);var iHeightHalf=(this.size.y*0.5);var translateX=this.pos.x+ iWidthHalf;var translateY=this.pos.y+ iHeightHalf;ctx.translate(translateX,translateY);var SX=this.scaleX;var SY=this.scaleY;ctx.scale(SX,SY);var drawX=-iWidthHalf- this.offset.x;var drawY=-iHeightHalf- this.offset.y;ctx.drawImage(this.currentImage.data,drawX,drawY);ctx.restore();}});});