(window._gsQueue||(window._gsQueue=[])).push(function(){"use strict";window._gsDefine("TimelineMax",["TimelineLite","TweenLite","easing.Ease"],function(TimelineLite,TweenLite,Ease){var TimelineMax=function(vars){TimelineLite.call(this,vars);this._repeat=this.vars.repeat||0;this._repeatDelay=this.vars.repeatDelay||0;this._cycle=0;this._yoyo=(this.vars.yoyo===true);this._dirty=true;},_tinyNum=0.0000000001,_blankArray=[],_easeNone=new Ease(null,null,1,0),p=TimelineMax.prototype=new TimelineLite();p.constructor=TimelineMax;p.kill()._gc=false;TimelineMax.version="1.11.4";p.invalidate=function(){this._yoyo=(this.vars.yoyo===true);this._repeat=this.vars.repeat||0;this._repeatDelay=this.vars.repeatDelay||0;this._uncache(true);return TimelineLite.prototype.invalidate.call(this);};p.addCallback=function(callback,position,params,scope){return this.add(TweenLite.delayedCall(0,callback,params,scope),position);};p.removeCallback=function(callback,position){if(callback){if(position==null){this._kill(null,callback);}else{var a=this.getTweensOf(callback,false),i=a.length,time=this._parseTimeOrLabel(position);while(--i>-1){if(a[i]._startTime===time){a[i]._enabled(false,false);}}}}
return this;};p.tweenTo=function(position,vars){vars=vars||{};var copy={ease:_easeNone,overwrite:2,useFrames:this.usesFrames(),immediateRender:false},duration,p,t;for(p in vars){copy[p]=vars[p];}
copy.time=this._parseTimeOrLabel(position);duration=(Math.abs(Number(copy.time)- this._time)/this._timeScale)||0.001;t=new TweenLite(this,duration,copy);copy.onStart=function(){t.target.paused(true);if(t.vars.time!==t.target.time()&&duration===t.duration()){t.duration(Math.abs(t.vars.time- t.target.time())/t.target._timeScale);}
if(vars.onStart){vars.onStart.apply(vars.onStartScope||t,vars.onStartParams||_blankArray);}};return t;};p.tweenFromTo=function(fromPosition,toPosition,vars){vars=vars||{};fromPosition=this._parseTimeOrLabel(fromPosition);vars.startAt={onComplete:this.seek,onCompleteParams:[fromPosition],onCompleteScope:this};vars.immediateRender=(vars.immediateRender!==false);var t=this.tweenTo(toPosition,vars);return t.duration((Math.abs(t.vars.time- fromPosition)/this._timeScale)||0.001);};p.render=function(time,suppressEvents,force){if(this._gc){this._enabled(true,false);}
var totalDur=(!this._dirty)?this._totalDuration:this.totalDuration(),dur=this._duration,prevTime=this._time,prevTotalTime=this._totalTime,prevStart=this._startTime,prevTimeScale=this._timeScale,prevRawPrevTime=this._rawPrevTime,prevPaused=this._paused,prevCycle=this._cycle,tween,isComplete,next,callback,internalForce,cycleDuration;if(time>=totalDur){if(!this._locked){this._totalTime=totalDur;this._cycle=this._repeat;}
if(!this._reversed)if(!this._hasPausedChild()){isComplete=true;callback="onComplete";if(this._duration===0)if(time===0||prevRawPrevTime<0||prevRawPrevTime===_tinyNum)if(prevRawPrevTime!==time&&this._first){internalForce=true;if(prevRawPrevTime>_tinyNum){callback="onReverseComplete";}}}
this._rawPrevTime=(this._duration||!suppressEvents||time||this._rawPrevTime===0)?time:_tinyNum;if(this._yoyo&&(this._cycle&1)!==0){this._time=time=0;}else{this._time=dur;time=dur+ 0.0001;}}else if(time<0.0000001){if(!this._locked){this._totalTime=this._cycle=0;}
this._time=0;if(prevTime!==0||(dur===0&&(prevRawPrevTime>_tinyNum||(time<0&&prevRawPrevTime>=0))&&!this._locked)){callback="onReverseComplete";isComplete=this._reversed;}
if(time<0){this._active=false;if(dur===0)if(prevRawPrevTime>=0&&this._first){internalForce=true;}
this._rawPrevTime=time;}else{this._rawPrevTime=(dur||!suppressEvents||time||this._rawPrevTime===0)?time:_tinyNum;time=0;if(!this._initted){internalForce=true;}}}else{if(dur===0&&prevRawPrevTime<0){internalForce=true;}
this._time=this._rawPrevTime=time;if(!this._locked){this._totalTime=time;if(this._repeat!==0){cycleDuration=dur+ this._repeatDelay;this._cycle=(this._totalTime/cycleDuration)>>0;if(this._cycle!==0)if(this._cycle===this._totalTime/cycleDuration){this._cycle--;}
this._time=this._totalTime-(this._cycle*cycleDuration);if(this._yoyo)if((this._cycle&1)!==0){this._time=dur- this._time;}
if(this._time>dur){this._time=dur;time=dur+ 0.0001;}else if(this._time<0){this._time=time=0;}else{time=this._time;}}}}
if(this._cycle!==prevCycle)if(!this._locked){var backwards=(this._yoyo&&(prevCycle&1)!==0),wrap=(backwards===(this._yoyo&&(this._cycle&1)!==0)),recTotalTime=this._totalTime,recCycle=this._cycle,recRawPrevTime=this._rawPrevTime,recTime=this._time;this._totalTime=prevCycle*dur;if(this._cycle<prevCycle){backwards=!backwards;}else{this._totalTime+=dur;}
this._time=prevTime;this._rawPrevTime=(dur===0)?prevRawPrevTime- 0.0001:prevRawPrevTime;this._cycle=prevCycle;this._locked=true;prevTime=(backwards)?0:dur;this.render(prevTime,suppressEvents,(dur===0));if(!suppressEvents)if(!this._gc){if(this.vars.onRepeat){this.vars.onRepeat.apply(this.vars.onRepeatScope||this,this.vars.onRepeatParams||_blankArray);}}
if(wrap){prevTime=(backwards)?dur+ 0.0001:-0.0001;this.render(prevTime,true,false);}
this._locked=false;if(this._paused&&!prevPaused){return;}
this._time=recTime;this._totalTime=recTotalTime;this._cycle=recCycle;this._rawPrevTime=recRawPrevTime;}
if((this._time===prevTime||!this._first)&&!force&&!internalForce){if(prevTotalTime!==this._totalTime)if(this._onUpdate)if(!suppressEvents){this._onUpdate.apply(this.vars.onUpdateScope||this,this.vars.onUpdateParams||_blankArray);}
return;}else if(!this._initted){this._initted=true;}
if(!this._active)if(!this._paused&&this._totalTime!==prevTotalTime&&time>0){this._active=true;}
if(prevTotalTime===0)if(this.vars.onStart)if(this._totalTime!==0)if(!suppressEvents){this.vars.onStart.apply(this.vars.onStartScope||this,this.vars.onStartParams||_blankArray);}
if(this._time>=prevTime){tween=this._first;while(tween){next=tween._next;if(this._paused&&!prevPaused){break;}else if(tween._active||(tween._startTime<=this._time&&!tween._paused&&!tween._gc)){if(!tween._reversed){tween.render((time- tween._startTime)*tween._timeScale,suppressEvents,force);}else{tween.render(((!tween._dirty)?tween._totalDuration:tween.totalDuration())-((time- tween._startTime)*tween._timeScale),suppressEvents,force);}}
tween=next;}}else{tween=this._last;while(tween){next=tween._prev;if(this._paused&&!prevPaused){break;}else if(tween._active||(tween._startTime<=prevTime&&!tween._paused&&!tween._gc)){if(!tween._reversed){tween.render((time- tween._startTime)*tween._timeScale,suppressEvents,force);}else{tween.render(((!tween._dirty)?tween._totalDuration:tween.totalDuration())-((time- tween._startTime)*tween._timeScale),suppressEvents,force);}}
tween=next;}}
if(this._onUpdate)if(!suppressEvents){this._onUpdate.apply(this.vars.onUpdateScope||this,this.vars.onUpdateParams||_blankArray);}
if(callback)if(!this._locked)if(!this._gc)if(prevStart===this._startTime||prevTimeScale!==this._timeScale)if(this._time===0||totalDur>=this.totalDuration()){if(isComplete){if(this._timeline.autoRemoveChildren){this._enabled(false,false);}
this._active=false;}
if(!suppressEvents&&this.vars[callback]){this.vars[callback].apply(this.vars[callback+"Scope"]||this,this.vars[callback+"Params"]||_blankArray);}}};p.getActive=function(nested,tweens,timelines){if(nested==null){nested=true;}
if(tweens==null){tweens=true;}
if(timelines==null){timelines=false;}
var a=[],all=this.getChildren(nested,tweens,timelines),cnt=0,l=all.length,i,tween;for(i=0;i<l;i++){tween=all[i];if(tween.isActive()){a[cnt++]=tween;}}
return a;};p.getLabelAfter=function(time){if(!time)if(time!==0){time=this._time;}
var labels=this.getLabelsArray(),l=labels.length,i;for(i=0;i<l;i++){if(labels[i].time>time){return labels[i].name;}}
return null;};p.getLabelBefore=function(time){if(time==null){time=this._time;}
var labels=this.getLabelsArray(),i=labels.length;while(--i>-1){if(labels[i].time<time){return labels[i].name;}}
return null;};p.getLabelsArray=function(){var a=[],cnt=0,p;for(p in this._labels){a[cnt++]={time:this._labels[p],name:p};}
a.sort(function(a,b){return a.time- b.time;});return a;};p.progress=function(value){return(!arguments.length)?this._time/this.duration():this.totalTime(this.duration()*((this._yoyo&&(this._cycle&1)!==0)?1- value:value)+(this._cycle*(this._duration+ this._repeatDelay)),false);};p.totalProgress=function(value){return(!arguments.length)?this._totalTime/this.totalDuration():this.totalTime(this.totalDuration()*value,false);};p.totalDuration=function(value){if(!arguments.length){if(this._dirty){TimelineLite.prototype.totalDuration.call(this);this._totalDuration=(this._repeat===-1)?999999999999:this._duration*(this._repeat+ 1)+(this._repeatDelay*this._repeat);}
return this._totalDuration;}
return(this._repeat===-1)?this:this.duration((value-(this._repeat*this._repeatDelay))/(this._repeat+ 1));};p.time=function(value,suppressEvents){if(!arguments.length){return this._time;}
if(this._dirty){this.totalDuration();}
if(value>this._duration){value=this._duration;}
if(this._yoyo&&(this._cycle&1)!==0){value=(this._duration- value)+(this._cycle*(this._duration+ this._repeatDelay));}else if(this._repeat!==0){value+=this._cycle*(this._duration+ this._repeatDelay);}
return this.totalTime(value,suppressEvents);};p.repeat=function(value){if(!arguments.length){return this._repeat;}
this._repeat=value;return this._uncache(true);};p.repeatDelay=function(value){if(!arguments.length){return this._repeatDelay;}
this._repeatDelay=value;return this._uncache(true);};p.yoyo=function(value){if(!arguments.length){return this._yoyo;}
this._yoyo=value;return this;};p.currentLabel=function(value){if(!arguments.length){return this.getLabelBefore(this._time+ 0.00000001);}
return this.seek(value,true);};return TimelineMax;},true);window._gsDefine("TimelineLite",["core.Animation","core.SimpleTimeline","TweenLite"],function(Animation,SimpleTimeline,TweenLite){var TimelineLite=function(vars){SimpleTimeline.call(this,vars);this._labels={};this.autoRemoveChildren=(this.vars.autoRemoveChildren===true);this.smoothChildTiming=(this.vars.smoothChildTiming===true);this._sortChildren=true;this._onUpdate=this.vars.onUpdate;var v=this.vars,val,p;for(p in v){val=v[p];if(_isArray(val))if(val.join("").indexOf("{self}")!==-1){v[p]=this._swapSelfInParams(val);}}
if(_isArray(v.tweens)){this.add(v.tweens,0,v.align,v.stagger);}},_tinyNum=0.0000000001,_isSelector=TweenLite._internals.isSelector,_isArray=TweenLite._internals.isArray,_blankArray=[],_copy=function(vars){var copy={},p;for(p in vars){copy[p]=vars[p];}
return copy;},_pauseCallback=function(tween,callback,params,scope){tween._timeline.pause(tween._startTime);if(callback){callback.apply(scope||tween._timeline,params||_blankArray);}},_slice=_blankArray.slice,p=TimelineLite.prototype=new SimpleTimeline();TimelineLite.version="1.11.4";p.constructor=TimelineLite;p.kill()._gc=false;p.to=function(target,duration,vars,position){return duration?this.add(new TweenLite(target,duration,vars),position):this.set(target,vars,position);};p.from=function(target,duration,vars,position){return this.add(TweenLite.from(target,duration,vars),position);};p.fromTo=function(target,duration,fromVars,toVars,position){return duration?this.add(TweenLite.fromTo(target,duration,fromVars,toVars),position):this.set(target,toVars,position);};p.staggerTo=function(targets,duration,vars,stagger,position,onCompleteAll,onCompleteAllParams,onCompleteAllScope){var tl=new TimelineLite({onComplete:onCompleteAll,onCompleteParams:onCompleteAllParams,onCompleteScope:onCompleteAllScope,smoothChildTiming:this.smoothChildTiming}),i;if(typeof(targets)==="string"){targets=TweenLite.selector(targets)||targets;}
if(_isSelector(targets)){targets=_slice.call(targets,0);}
stagger=stagger||0;for(i=0;i<targets.length;i++){if(vars.startAt){vars.startAt=_copy(vars.startAt);}
tl.to(targets[i],duration,_copy(vars),i*stagger);}
return this.add(tl,position);};p.staggerFrom=function(targets,duration,vars,stagger,position,onCompleteAll,onCompleteAllParams,onCompleteAllScope){vars.immediateRender=(vars.immediateRender!=false);vars.runBackwards=true;return this.staggerTo(targets,duration,vars,stagger,position,onCompleteAll,onCompleteAllParams,onCompleteAllScope);};p.staggerFromTo=function(targets,duration,fromVars,toVars,stagger,position,onCompleteAll,onCompleteAllParams,onCompleteAllScope){toVars.startAt=fromVars;toVars.immediateRender=(toVars.immediateRender!=false&&fromVars.immediateRender!=false);return this.staggerTo(targets,duration,toVars,stagger,position,onCompleteAll,onCompleteAllParams,onCompleteAllScope);};p.call=function(callback,params,scope,position){return this.add(TweenLite.delayedCall(0,callback,params,scope),position);};p.set=function(target,vars,position){position=this._parseTimeOrLabel(position,0,true);if(vars.immediateRender==null){vars.immediateRender=(position===this._time&&!this._paused);}
return this.add(new TweenLite(target,0,vars),position);};TimelineLite.exportRoot=function(vars,ignoreDelayedCalls){vars=vars||{};if(vars.smoothChildTiming==null){vars.smoothChildTiming=true;}
var tl=new TimelineLite(vars),root=tl._timeline,tween,next;if(ignoreDelayedCalls==null){ignoreDelayedCalls=true;}
root._remove(tl,true);tl._startTime=0;tl._rawPrevTime=tl._time=tl._totalTime=root._time;tween=root._first;while(tween){next=tween._next;if(!ignoreDelayedCalls||!(tween instanceof TweenLite&&tween.target===tween.vars.onComplete)){tl.add(tween,tween._startTime- tween._delay);}
tween=next;}
root.add(tl,0);return tl;};p.add=function(value,position,align,stagger){var curTime,l,i,child,tl,beforeRawTime;if(typeof(position)!=="number"){position=this._parseTimeOrLabel(position,0,true,value);}
if(!(value instanceof Animation)){if((value instanceof Array)||(value&&value.push&&_isArray(value))){align=align||"normal";stagger=stagger||0;curTime=position;l=value.length;for(i=0;i<l;i++){if(_isArray(child=value[i])){child=new TimelineLite({tweens:child});}
this.add(child,curTime);if(typeof(child)!=="string"&&typeof(child)!=="function"){if(align==="sequence"){curTime=child._startTime+(child.totalDuration()/child._timeScale);}else if(align==="start"){child._startTime-=child.delay();}}
curTime+=stagger;}
return this._uncache(true);}else if(typeof(value)==="string"){return this.addLabel(value,position);}else if(typeof(value)==="function"){value=TweenLite.delayedCall(0,value);}else{throw("Cannot add "+ value+" into the timeline; it is not a tween, timeline, function, or string.");}}
SimpleTimeline.prototype.add.call(this,value,position);if(this._gc)if(!this._paused)if(this._duration<this.duration()){tl=this;beforeRawTime=(tl.rawTime()>value._startTime);while(tl._gc&&tl._timeline){if(tl._timeline.smoothChildTiming&&beforeRawTime){tl.totalTime(tl._totalTime,true);}else{tl._enabled(true,false);}
tl=tl._timeline;}}
return this;};p.remove=function(value){if(value instanceof Animation){return this._remove(value,false);}else if(value instanceof Array||(value&&value.push&&_isArray(value))){var i=value.length;while(--i>-1){this.remove(value[i]);}
return this;}else if(typeof(value)==="string"){return this.removeLabel(value);}
return this.kill(null,value);};p._remove=function(tween,skipDisable){SimpleTimeline.prototype._remove.call(this,tween,skipDisable);var last=this._last;if(!last){this._time=this._totalTime=0;}else if(this._time>last._startTime+ last._totalDuration/last._timeScale){this._time=this.duration();this._totalTime=this._totalDuration;}
return this;};p.append=function(value,offsetOrLabel){return this.add(value,this._parseTimeOrLabel(null,offsetOrLabel,true,value));};p.insert=p.insertMultiple=function(value,position,align,stagger){return this.add(value,position||0,align,stagger);};p.appendMultiple=function(tweens,offsetOrLabel,align,stagger){return this.add(tweens,this._parseTimeOrLabel(null,offsetOrLabel,true,tweens),align,stagger);};p.addLabel=function(label,position){this._labels[label]=this._parseTimeOrLabel(position);return this;};p.addPause=function(position,callback,params,scope){return this.call(_pauseCallback,["{self}",callback,params,scope],this,position);};p.removeLabel=function(label){delete this._labels[label];return this;};p.getLabelTime=function(label){return(this._labels[label]!=null)?this._labels[label]:-1;};p._parseTimeOrLabel=function(timeOrLabel,offsetOrLabel,appendIfAbsent,ignore){var i;if(ignore instanceof Animation&&ignore.timeline===this){this.remove(ignore);}else if(ignore&&((ignore instanceof Array)||(ignore.push&&_isArray(ignore)))){i=ignore.length;while(--i>-1){if(ignore[i]instanceof Animation&&ignore[i].timeline===this){this.remove(ignore[i]);}}}
if(typeof(offsetOrLabel)==="string"){return this._parseTimeOrLabel(offsetOrLabel,(appendIfAbsent&&typeof(timeOrLabel)==="number"&&this._labels[offsetOrLabel]==null)?timeOrLabel- this.duration():0,appendIfAbsent);}
offsetOrLabel=offsetOrLabel||0;if(typeof(timeOrLabel)==="string"&&(isNaN(timeOrLabel)||this._labels[timeOrLabel]!=null)){i=timeOrLabel.indexOf("=");if(i===-1){if(this._labels[timeOrLabel]==null){return appendIfAbsent?(this._labels[timeOrLabel]=this.duration()+ offsetOrLabel):offsetOrLabel;}
return this._labels[timeOrLabel]+ offsetOrLabel;}
offsetOrLabel=parseInt(timeOrLabel.charAt(i-1)+"1",10)*Number(timeOrLabel.substr(i+1));timeOrLabel=(i>1)?this._parseTimeOrLabel(timeOrLabel.substr(0,i-1),0,appendIfAbsent):this.duration();}else if(timeOrLabel==null){timeOrLabel=this.duration();}
return Number(timeOrLabel)+ offsetOrLabel;};p.seek=function(position,suppressEvents){return this.totalTime((typeof(position)==="number")?position:this._parseTimeOrLabel(position),(suppressEvents!==false));};p.stop=function(){return this.paused(true);};p.gotoAndPlay=function(position,suppressEvents){return this.play(position,suppressEvents);};p.gotoAndStop=function(position,suppressEvents){return this.pause(position,suppressEvents);};p.render=function(time,suppressEvents,force){if(this._gc){this._enabled(true,false);}
var totalDur=(!this._dirty)?this._totalDuration:this.totalDuration(),prevTime=this._time,prevStart=this._startTime,prevTimeScale=this._timeScale,prevPaused=this._paused,tween,isComplete,next,callback,internalForce;if(time>=totalDur){this._totalTime=this._time=totalDur;if(!this._reversed)if(!this._hasPausedChild()){isComplete=true;callback="onComplete";if(this._duration===0)if(time===0||this._rawPrevTime<0||this._rawPrevTime===_tinyNum)if(this._rawPrevTime!==time&&this._first){internalForce=true;if(this._rawPrevTime>_tinyNum){callback="onReverseComplete";}}}
this._rawPrevTime=(this._duration||!suppressEvents||time||this._rawPrevTime===0)?time:_tinyNum;time=totalDur+ 0.0001;}else if(time<0.0000001){this._totalTime=this._time=0;if(prevTime!==0||(this._duration===0&&(this._rawPrevTime>_tinyNum||(time<0&&this._rawPrevTime>=0)))){callback="onReverseComplete";isComplete=this._reversed;}
if(time<0){this._active=false;if(this._duration===0)if(this._rawPrevTime>=0&&this._first){internalForce=true;}
this._rawPrevTime=time;}else{this._rawPrevTime=(this._duration||!suppressEvents||time||this._rawPrevTime===0)?time:_tinyNum;time=0;if(!this._initted){internalForce=true;}}}else{this._totalTime=this._time=this._rawPrevTime=time;}
if((this._time===prevTime||!this._first)&&!force&&!internalForce){return;}else if(!this._initted){this._initted=true;}
if(!this._active)if(!this._paused&&this._time!==prevTime&&time>0){this._active=true;}
if(prevTime===0)if(this.vars.onStart)if(this._time!==0)if(!suppressEvents){this.vars.onStart.apply(this.vars.onStartScope||this,this.vars.onStartParams||_blankArray);}
if(this._time>=prevTime){tween=this._first;while(tween){next=tween._next;if(this._paused&&!prevPaused){break;}else if(tween._active||(tween._startTime<=this._time&&!tween._paused&&!tween._gc)){if(!tween._reversed){tween.render((time- tween._startTime)*tween._timeScale,suppressEvents,force);}else{tween.render(((!tween._dirty)?tween._totalDuration:tween.totalDuration())-((time- tween._startTime)*tween._timeScale),suppressEvents,force);}}
tween=next;}}else{tween=this._last;while(tween){next=tween._prev;if(this._paused&&!prevPaused){break;}else if(tween._active||(tween._startTime<=prevTime&&!tween._paused&&!tween._gc)){if(!tween._reversed){tween.render((time- tween._startTime)*tween._timeScale,suppressEvents,force);}else{tween.render(((!tween._dirty)?tween._totalDuration:tween.totalDuration())-((time- tween._startTime)*tween._timeScale),suppressEvents,force);}}
tween=next;}}
if(this._onUpdate)if(!suppressEvents){this._onUpdate.apply(this.vars.onUpdateScope||this,this.vars.onUpdateParams||_blankArray);}
if(callback)if(!this._gc)if(prevStart===this._startTime||prevTimeScale!==this._timeScale)if(this._time===0||totalDur>=this.totalDuration()){if(isComplete){if(this._timeline.autoRemoveChildren){this._enabled(false,false);}
this._active=false;}
if(!suppressEvents&&this.vars[callback]){this.vars[callback].apply(this.vars[callback+"Scope"]||this,this.vars[callback+"Params"]||_blankArray);}}};p._hasPausedChild=function(){var tween=this._first;while(tween){if(tween._paused||((tween instanceof TimelineLite)&&tween._hasPausedChild())){return true;}
tween=tween._next;}
return false;};p.getChildren=function(nested,tweens,timelines,ignoreBeforeTime){ignoreBeforeTime=ignoreBeforeTime||-9999999999;var a=[],tween=this._first,cnt=0;while(tween){if(tween._startTime<ignoreBeforeTime){}else if(tween instanceof TweenLite){if(tweens!==false){a[cnt++]=tween;}}else{if(timelines!==false){a[cnt++]=tween;}
if(nested!==false){a=a.concat(tween.getChildren(true,tweens,timelines));cnt=a.length;}}
tween=tween._next;}
return a;};p.getTweensOf=function(target,nested){var tweens=TweenLite.getTweensOf(target),i=tweens.length,a=[],cnt=0;while(--i>-1){if(tweens[i].timeline===this||(nested&&this._contains(tweens[i]))){a[cnt++]=tweens[i];}}
return a;};p._contains=function(tween){var tl=tween.timeline;while(tl){if(tl===this){return true;}
tl=tl.timeline;}
return false;};p.shiftChildren=function(amount,adjustLabels,ignoreBeforeTime){ignoreBeforeTime=ignoreBeforeTime||0;var tween=this._first,labels=this._labels,p;while(tween){if(tween._startTime>=ignoreBeforeTime){tween._startTime+=amount;}
tween=tween._next;}
if(adjustLabels){for(p in labels){if(labels[p]>=ignoreBeforeTime){labels[p]+=amount;}}}
return this._uncache(true);};p._kill=function(vars,target){if(!vars&&!target){return this._enabled(false,false);}
var tweens=(!target)?this.getChildren(true,true,false):this.getTweensOf(target),i=tweens.length,changed=false;while(--i>-1){if(tweens[i]._kill(vars,target)){changed=true;}}
return changed;};p.clear=function(labels){var tweens=this.getChildren(false,true,true),i=tweens.length;this._time=this._totalTime=0;while(--i>-1){tweens[i]._enabled(false,false);}
if(labels!==false){this._labels={};}
return this._uncache(true);};p.invalidate=function(){var tween=this._first;while(tween){tween.invalidate();tween=tween._next;}
return this;};p._enabled=function(enabled,ignoreTimeline){if(enabled===this._gc){var tween=this._first;while(tween){tween._enabled(enabled,true);tween=tween._next;}}
return SimpleTimeline.prototype._enabled.call(this,enabled,ignoreTimeline);};p.duration=function(value){if(!arguments.length){if(this._dirty){this.totalDuration();}
return this._duration;}
if(this.duration()!==0&&value!==0){this.timeScale(this._duration/value);}
return this;};p.totalDuration=function(value){if(!arguments.length){if(this._dirty){var max=0,tween=this._last,prevStart=999999999999,prev,end;while(tween){prev=tween._prev;if(tween._dirty){tween.totalDuration();}
if(tween._startTime>prevStart&&this._sortChildren&&!tween._paused){this.add(tween,tween._startTime- tween._delay);}else{prevStart=tween._startTime;}
if(tween._startTime<0&&!tween._paused){max-=tween._startTime;if(this._timeline.smoothChildTiming){this._startTime+=tween._startTime/this._timeScale;}
this.shiftChildren(-tween._startTime,false,-9999999999);prevStart=0;}
end=tween._startTime+(tween._totalDuration/tween._timeScale);if(end>max){max=end;}
tween=prev;}
this._duration=this._totalDuration=max;this._dirty=false;}
return this._totalDuration;}
if(this.totalDuration()!==0)if(value!==0){this.timeScale(this._totalDuration/value);}
return this;};p.usesFrames=function(){var tl=this._timeline;while(tl._timeline){tl=tl._timeline;}
return(tl===Animation._rootFramesTimeline);};p.rawTime=function(){return this._paused?this._totalTime:(this._timeline.rawTime()- this._startTime)*this._timeScale;};return TimelineLite;},true);});if(window._gsDefine){window._gsQueue.pop()();}