(window._gsQueue||(window._gsQueue=[])).push(function(){"use strict";window._gsDefine("plugins.CSSPlugin",["plugins.TweenPlugin","TweenLite"],function(TweenPlugin,TweenLite){var CSSPlugin=function(){TweenPlugin.call(this,"css");this._overwriteProps.length=0;this.setRatio=CSSPlugin.prototype.setRatio;},_hasPriority,_suffixMap,_cs,_overwriteProps,_specialProps={},p=CSSPlugin.prototype=new TweenPlugin("css");p.constructor=CSSPlugin;CSSPlugin.version="1.11.4";CSSPlugin.API=2;CSSPlugin.defaultTransformPerspective=0;p="px";CSSPlugin.suffixMap={top:p,right:p,bottom:p,left:p,width:p,height:p,fontSize:p,padding:p,margin:p,perspective:p,lineHeight:""};var _numExp=/(?:\d|\-\d|\.\d|\-\.\d)+/g,_relNumExp=/(?:\d|\-\d|\.\d|\-\.\d|\+=\d|\-=\d|\+=.\d|\-=\.\d)+/g,_valuesExp=/(?:\+=|\-=|\-|\b)[\d\-\.]+[a-zA-Z0-9]*(?:%|\b)/gi,_NaNExp=/[^\d\-\.]/g,_suffixExp=/(?:\d|\-|\+|=|#|\.)*/g,_opacityExp=/opacity *= *([^)]*)/,_opacityValExp=/opacity:([^;]*)/,_alphaFilterExp=/alpha\(opacity *=.+?\)/i,_rgbhslExp=/^(rgb|hsl)/,_capsExp=/([A-Z])/g,_camelExp=/-([a-z])/gi,_urlExp=/(^(?:url\(\"|url\())|(?:(\"\))$|\)$)/gi,_camelFunc=function(s,g){return g.toUpperCase();},_horizExp=/(?:Left|Right|Width)/i,_ieGetMatrixExp=/(M11|M12|M21|M22)=[\d\-\.e]+/gi,_ieSetMatrixExp=/progid\:DXImageTransform\.Microsoft\.Matrix\(.+?\)/i,_commasOutsideParenExp=/,(?=[^\)]*(?:\(|$))/gi,_DEG2RAD=Math.PI/180,_RAD2DEG=180/Math.PI,_forcePT={},_doc=document,_tempDiv=_doc.createElement("div"),_tempImg=_doc.createElement("img"),_internals=CSSPlugin._internals={_specialProps:_specialProps},_agent=navigator.userAgent,_autoRound,_reqSafariFix,_isSafari,_isFirefox,_isSafariLT6,_ieVers,_supportsOpacity=(function(){var i=_agent.indexOf("Android"),d=_doc.createElement("div"),a;_isSafari=(_agent.indexOf("Safari")!==-1&&_agent.indexOf("Chrome")===-1&&(i===-1||Number(_agent.substr(i+8,1))>3));_isSafariLT6=(_isSafari&&(Number(_agent.substr(_agent.indexOf("Version/")+8,1))<6));_isFirefox=(_agent.indexOf("Firefox")!==-1);if((/MSIE ([0-9]{1,}[\.0-9]{0,})/).exec(_agent)){_ieVers=parseFloat(RegExp.$1);}
d.innerHTML="<a style='top:1px;opacity:.55;'>a</a>";a=d.getElementsByTagName("a")[0];return a?/^0.55/.test(a.style.opacity):false;}()),_getIEOpacity=function(v){return(_opacityExp.test(((typeof(v)==="string")?v:(v.currentStyle?v.currentStyle.filter:v.style.filter)||""))?(parseFloat(RegExp.$1)/100):1);},_log=function(s){if(window.console){console.log(s);}},_prefixCSS="",_prefix="",_checkPropPrefix=function(p,e){e=e||_tempDiv;var s=e.style,a,i;if(s[p]!==undefined){return p;}
p=p.charAt(0).toUpperCase()+ p.substr(1);a=["O","Moz","ms","Ms","Webkit"];i=5;while(--i>-1&&s[a[i]+p]===undefined){}
if(i>=0){_prefix=(i===3)?"ms":a[i];_prefixCSS="-"+ _prefix.toLowerCase()+"-";return _prefix+ p;}
return null;},_getComputedStyle=_doc.defaultView?_doc.defaultView.getComputedStyle:function(){},_getStyle=CSSPlugin.getStyle=function(t,p,cs,calc,dflt){var rv;if(!_supportsOpacity)if(p==="opacity"){return _getIEOpacity(t);}
if(!calc&&t.style[p]){rv=t.style[p];}else if((cs=cs||_getComputedStyle(t,null))){t=cs.getPropertyValue(p.replace(_capsExp,"-$1").toLowerCase());rv=(t||cs.length)?t:cs[p];}else if(t.currentStyle){rv=t.currentStyle[p];}
return(dflt!=null&&(!rv||rv==="none"||rv==="auto"||rv==="auto auto"))?dflt:rv;},_convertToPixels=function(t,p,v,sfx,recurse){if(sfx==="px"||!sfx){return v;}
if(sfx==="auto"||!v){return 0;}
var horiz=_horizExp.test(p),node=t,style=_tempDiv.style,neg=(v<0),pix;if(neg){v=-v;}
if(sfx==="%"&&p.indexOf("border")!==-1){pix=(v/100)*(horiz?t.clientWidth:t.clientHeight);}else{style.cssText="border:0 solid red;position:"+ _getStyle(t,"position")+";line-height:0;";if(sfx==="%"||!node.appendChild){node=t.parentNode||_doc.body;style[(horiz?"width":"height")]=v+ sfx;}else{style[(horiz?"borderLeftWidth":"borderTopWidth")]=v+ sfx;}
node.appendChild(_tempDiv);pix=parseFloat(_tempDiv[(horiz?"offsetWidth":"offsetHeight")]);node.removeChild(_tempDiv);if(pix===0&&!recurse){pix=_convertToPixels(t,p,v,sfx,true);}}
return neg?-pix:pix;},_calculateOffset=function(t,p,cs){if(_getStyle(t,"position",cs)!=="absolute"){return 0;}
var dim=((p==="left")?"Left":"Top"),v=_getStyle(t,"margin"+ dim,cs);return t["offset"+ dim]-(_convertToPixels(t,p,parseFloat(v),v.replace(_suffixExp,""))||0);},_getAllStyles=function(t,cs){var s={},i,tr;if((cs=cs||_getComputedStyle(t,null))){if((i=cs.length)){while(--i>-1){s[cs[i].replace(_camelExp,_camelFunc)]=cs.getPropertyValue(cs[i]);}}else{for(i in cs){s[i]=cs[i];}}}else if((cs=t.currentStyle||t.style)){for(i in cs){if(typeof(i)==="string"&&s[i]!==undefined){s[i.replace(_camelExp,_camelFunc)]=cs[i];}}}
if(!_supportsOpacity){s.opacity=_getIEOpacity(t);}
tr=_getTransform(t,cs,false);s.rotation=tr.rotation;s.skewX=tr.skewX;s.scaleX=tr.scaleX;s.scaleY=tr.scaleY;s.x=tr.x;s.y=tr.y;if(_supports3D){s.z=tr.z;s.rotationX=tr.rotationX;s.rotationY=tr.rotationY;s.scaleZ=tr.scaleZ;}
if(s.filters){delete s.filters;}
return s;},_cssDif=function(t,s1,s2,vars,forceLookup){var difs={},style=t.style,val,p,mpt;for(p in s2){if(p!=="cssText")if(p!=="length")if(isNaN(p))if(s1[p]!==(val=s2[p])||(forceLookup&&forceLookup[p]))if(p.indexOf("Origin")===-1)if(typeof(val)==="number"||typeof(val)==="string"){difs[p]=(val==="auto"&&(p==="left"||p==="top"))?_calculateOffset(t,p):((val===""||val==="auto"||val==="none")&&typeof(s1[p])==="string"&&s1[p].replace(_NaNExp,"")!=="")?0:val;if(style[p]!==undefined){mpt=new MiniPropTween(style,p,style[p],mpt);}}}
if(vars){for(p in vars){if(p!=="className"){difs[p]=vars[p];}}}
return{difs:difs,firstMPT:mpt};},_dimensions={width:["Left","Right"],height:["Top","Bottom"]},_margins=["marginLeft","marginRight","marginTop","marginBottom"],_getDimension=function(t,p,cs){var v=parseFloat((p==="width")?t.offsetWidth:t.offsetHeight),a=_dimensions[p],i=a.length;cs=cs||_getComputedStyle(t,null);while(--i>-1){v-=parseFloat(_getStyle(t,"padding"+ a[i],cs,true))||0;v-=parseFloat(_getStyle(t,"border"+ a[i]+"Width",cs,true))||0;}
return v;},_parsePosition=function(v,recObj){if(v==null||v===""||v==="auto"||v==="auto auto"){v="0 0";}
var a=v.split(" "),x=(v.indexOf("left")!==-1)?"0%":(v.indexOf("right")!==-1)?"100%":a[0],y=(v.indexOf("top")!==-1)?"0%":(v.indexOf("bottom")!==-1)?"100%":a[1];if(y==null){y="0";}else if(y==="center"){y="50%";}
if(x==="center"||(isNaN(parseFloat(x))&&(x+"").indexOf("=")===-1)){x="50%";}
if(recObj){recObj.oxp=(x.indexOf("%")!==-1);recObj.oyp=(y.indexOf("%")!==-1);recObj.oxr=(x.charAt(1)==="=");recObj.oyr=(y.charAt(1)==="=");recObj.ox=parseFloat(x.replace(_NaNExp,""));recObj.oy=parseFloat(y.replace(_NaNExp,""));}
return x+" "+ y+((a.length>2)?" "+ a[2]:"");},_parseChange=function(e,b){return(typeof(e)==="string"&&e.charAt(1)==="=")?parseInt(e.charAt(0)+"1",10)*parseFloat(e.substr(2)):parseFloat(e)- parseFloat(b);},_parseVal=function(v,d){return(v==null)?d:(typeof(v)==="string"&&v.charAt(1)==="=")?parseInt(v.charAt(0)+"1",10)*Number(v.substr(2))+ d:parseFloat(v);},_parseAngle=function(v,d,p,directionalEnd){var min=0.000001,cap,split,dif,result;if(v==null){result=d;}else if(typeof(v)==="number"){result=v;}else{cap=360;split=v.split("_");dif=Number(split[0].replace(_NaNExp,""))*((v.indexOf("rad")===-1)?1:_RAD2DEG)-((v.charAt(1)==="=")?0:d);if(split.length){if(directionalEnd){directionalEnd[p]=d+ dif;}
if(v.indexOf("short")!==-1){dif=dif%cap;if(dif!==dif%(cap/2)){dif=(dif<0)?dif+ cap:dif- cap;}}
if(v.indexOf("_cw")!==-1&&dif<0){dif=((dif+ cap*9999999999)%cap)-((dif/cap)|0)*cap;}else if(v.indexOf("ccw")!==-1&&dif>0){dif=((dif- cap*9999999999)%cap)-((dif/cap)|0)*cap;}}
result=d+ dif;}
if(result<min&&result>-min){result=0;}
return result;},_colorLookup={aqua:[0,255,255],lime:[0,255,0],silver:[192,192,192],black:[0,0,0],maroon:[128,0,0],teal:[0,128,128],blue:[0,0,255],navy:[0,0,128],white:[255,255,255],fuchsia:[255,0,255],olive:[128,128,0],yellow:[255,255,0],orange:[255,165,0],gray:[128,128,128],purple:[128,0,128],green:[0,128,0],red:[255,0,0],pink:[255,192,203],cyan:[0,255,255],transparent:[255,255,255,0]},_hue=function(h,m1,m2){h=(h<0)?h+ 1:(h>1)?h- 1:h;return((((h*6<1)?m1+(m2- m1)*h*6:(h<0.5)?m2:(h*3<2)?m1+(m2- m1)*(2/3- h)*6:m1)*255)+ 0.5)|0;},_parseColor=function(v){var c1,c2,c3,h,s,l;if(!v||v===""){return _colorLookup.black;}
if(typeof(v)==="number"){return[v>>16,(v>>8)&255,v&255];}
if(v.charAt(v.length- 1)===","){v=v.substr(0,v.length- 1);}
if(_colorLookup[v]){return _colorLookup[v];}
if(v.charAt(0)==="#"){if(v.length===4){c1=v.charAt(1),c2=v.charAt(2),c3=v.charAt(3);v="#"+ c1+ c1+ c2+ c2+ c3+ c3;}
v=parseInt(v.substr(1),16);return[v>>16,(v>>8)&255,v&255];}
if(v.substr(0,3)==="hsl"){v=v.match(_numExp);h=(Number(v[0])%360)/360;s=Number(v[1])/100;l=Number(v[2])/100;c2=(l<=0.5)?l*(s+ 1):l+ s- l*s;c1=l*2- c2;if(v.length>3){v[3]=Number(v[3]);}
v[0]=_hue(h+ 1/3,c1,c2);v[1]=_hue(h,c1,c2);v[2]=_hue(h- 1/3,c1,c2);return v;}
v=v.match(_numExp)||_colorLookup.transparent;v[0]=Number(v[0]);v[1]=Number(v[1]);v[2]=Number(v[2]);if(v.length>3){v[3]=Number(v[3]);}
return v;},_colorExp="(?:\\b(?:(?:rgb|rgba|hsl|hsla)\\(.+?\\))|\\B#.+?\\b";for(p in _colorLookup){_colorExp+="|"+ p+"\\b";}
_colorExp=new RegExp(_colorExp+")","gi");var _getFormatter=function(dflt,clr,collapsible,multi){if(dflt==null){return function(v){return v;};}
var dColor=clr?(dflt.match(_colorExp)||[""])[0]:"",dVals=dflt.split(dColor).join("").match(_valuesExp)||[],pfx=dflt.substr(0,dflt.indexOf(dVals[0])),sfx=(dflt.charAt(dflt.length- 1)===")")?")":"",delim=(dflt.indexOf(" ")!==-1)?" ":",",numVals=dVals.length,dSfx=(numVals>0)?dVals[0].replace(_numExp,""):"",formatter;if(!numVals){return function(v){return v;};}
if(clr){formatter=function(v){var color,vals,i,a;if(typeof(v)==="number"){v+=dSfx;}else if(multi&&_commasOutsideParenExp.test(v)){a=v.replace(_commasOutsideParenExp,"|").split("|");for(i=0;i<a.length;i++){a[i]=formatter(a[i]);}
return a.join(",");}
color=(v.match(_colorExp)||[dColor])[0];vals=v.split(color).join("").match(_valuesExp)||[];i=vals.length;if(numVals>i--){while(++i<numVals){vals[i]=collapsible?vals[(((i- 1)/2)|0)]:dVals[i];}}
return pfx+ vals.join(delim)+ delim+ color+ sfx+(v.indexOf("inset")!==-1?" inset":"");};return formatter;}
formatter=function(v){var vals,a,i;if(typeof(v)==="number"){v+=dSfx;}else if(multi&&_commasOutsideParenExp.test(v)){a=v.replace(_commasOutsideParenExp,"|").split("|");for(i=0;i<a.length;i++){a[i]=formatter(a[i]);}
return a.join(",");}
vals=v.match(_valuesExp)||[];i=vals.length;if(numVals>i--){while(++i<numVals){vals[i]=collapsible?vals[(((i- 1)/2)|0)]:dVals[i];}}
return pfx+ vals.join(delim)+ sfx;};return formatter;},_getEdgeParser=function(props){props=props.split(",");return function(t,e,p,cssp,pt,plugin,vars){var a=(e+"").split(" "),i;vars={};for(i=0;i<4;i++){vars[props[i]]=a[i]=a[i]||a[(((i- 1)/2)>>0)];}
return cssp.parse(t,vars,pt,plugin);};},_setPluginRatio=_internals._setPluginRatio=function(v){this.plugin.setRatio(v);var d=this.data,proxy=d.proxy,mpt=d.firstMPT,min=0.000001,val,pt,i,str;while(mpt){val=proxy[mpt.v];if(mpt.r){val=(val>0)?(val+ 0.5)|0:(val- 0.5)|0;}else if(val<min&&val>-min){val=0;}
mpt.t[mpt.p]=val;mpt=mpt._next;}
if(d.autoRotate){d.autoRotate.rotation=proxy.rotation;}
if(v===1){mpt=d.firstMPT;while(mpt){pt=mpt.t;if(!pt.type){pt.e=pt.s+ pt.xs0;}else if(pt.type===1){str=pt.xs0+ pt.s+ pt.xs1;for(i=1;i<pt.l;i++){str+=pt["xn"+i]+ pt["xs"+(i+1)];}
pt.e=str;}
mpt=mpt._next;}}},MiniPropTween=function(t,p,v,next,r){this.t=t;this.p=p;this.v=v;this.r=r;if(next){next._prev=this;this._next=next;}},_parseToProxy=_internals._parseToProxy=function(t,vars,cssp,pt,plugin,shallow){var bpt=pt,start={},end={},transform=cssp._transform,oldForce=_forcePT,i,p,xp,mpt,firstPT;cssp._transform=null;_forcePT=vars;pt=firstPT=cssp.parse(t,vars,pt,plugin);_forcePT=oldForce;if(shallow){cssp._transform=transform;if(bpt){bpt._prev=null;if(bpt._prev){bpt._prev._next=null;}}}
while(pt&&pt!==bpt){if(pt.type<=1){p=pt.p;end[p]=pt.s+ pt.c;start[p]=pt.s;if(!shallow){mpt=new MiniPropTween(pt,"s",p,mpt,pt.r);pt.c=0;}
if(pt.type===1){i=pt.l;while(--i>0){xp="xn"+ i;p=pt.p+"_"+ xp;end[p]=pt.data[xp];start[p]=pt[xp];if(!shallow){mpt=new MiniPropTween(pt,xp,p,mpt,pt.rxp[xp]);}}}}
pt=pt._next;}
return{proxy:start,end:end,firstMPT:mpt,pt:firstPT};},CSSPropTween=_internals.CSSPropTween=function(t,p,s,c,next,type,n,r,pr,b,e){this.t=t;this.p=p;this.s=s;this.c=c;this.n=n||p;if(!(t instanceof CSSPropTween)){_overwriteProps.push(this.n);}
this.r=r;this.type=type||0;if(pr){this.pr=pr;_hasPriority=true;}
this.b=(b===undefined)?s:b;this.e=(e===undefined)?s+ c:e;if(next){this._next=next;next._prev=this;}},_parseComplex=CSSPlugin.parseComplex=function(t,p,b,e,clrs,dflt,pt,pr,plugin,setRatio){b=b||dflt||"";pt=new CSSPropTween(t,p,0,0,pt,(setRatio?2:1),null,false,pr,b,e);e+="";var ba=b.split(", ").join(",").split(" "),ea=e.split(", ").join(",").split(" "),l=ba.length,autoRound=(_autoRound!==false),i,xi,ni,bv,ev,bnums,enums,bn,rgba,temp,cv,str;if(e.indexOf(",")!==-1||b.indexOf(",")!==-1){ba=ba.join(" ").replace(_commasOutsideParenExp,", ").split(" ");ea=ea.join(" ").replace(_commasOutsideParenExp,", ").split(" ");l=ba.length;}
if(l!==ea.length){ba=(dflt||"").split(" ");l=ba.length;}
pt.plugin=plugin;pt.setRatio=setRatio;for(i=0;i<l;i++){bv=ba[i];ev=ea[i];bn=parseFloat(bv);if(bn||bn===0){pt.appendXtra("",bn,_parseChange(ev,bn),ev.replace(_relNumExp,""),(autoRound&&ev.indexOf("px")!==-1),true);}else if(clrs&&(bv.charAt(0)==="#"||_colorLookup[bv]||_rgbhslExp.test(bv))){str=ev.charAt(ev.length- 1)===","?"),":")";bv=_parseColor(bv);ev=_parseColor(ev);rgba=(bv.length+ ev.length>6);if(rgba&&!_supportsOpacity&&ev[3]===0){pt["xs"+ pt.l]+=pt.l?" transparent":"transparent";pt.e=pt.e.split(ea[i]).join("transparent");}else{if(!_supportsOpacity){rgba=false;}
pt.appendXtra((rgba?"rgba(":"rgb("),bv[0],ev[0]- bv[0],",",true,true).appendXtra("",bv[1],ev[1]- bv[1],",",true).appendXtra("",bv[2],ev[2]- bv[2],(rgba?",":str),true);if(rgba){bv=(bv.length<4)?1:bv[3];pt.appendXtra("",bv,((ev.length<4)?1:ev[3])- bv,str,false);}}}else{bnums=bv.match(_numExp);if(!bnums){pt["xs"+ pt.l]+=pt.l?" "+ bv:bv;}else{enums=ev.match(_relNumExp);if(!enums||enums.length!==bnums.length){return pt;}
ni=0;for(xi=0;xi<bnums.length;xi++){cv=bnums[xi];temp=bv.indexOf(cv,ni);pt.appendXtra(bv.substr(ni,temp- ni),Number(cv),_parseChange(enums[xi],cv),"",(autoRound&&bv.substr(temp+ cv.length,2)==="px"),(xi===0));ni=temp+ cv.length;}
pt["xs"+ pt.l]+=bv.substr(ni);}}}
if(e.indexOf("=")!==-1)if(pt.data){str=pt.xs0+ pt.data.s;for(i=1;i<pt.l;i++){str+=pt["xs"+ i]+ pt.data["xn"+ i];}
pt.e=str+ pt["xs"+ i];}
if(!pt.l){pt.type=-1;pt.xs0=pt.e;}
return pt.xfirst||pt;},i=9;p=CSSPropTween.prototype;p.l=p.pr=0;while(--i>0){p["xn"+ i]=0;p["xs"+ i]="";}
p.xs0="";p._next=p._prev=p.xfirst=p.data=p.plugin=p.setRatio=p.rxp=null;p.appendXtra=function(pfx,s,c,sfx,r,pad){var pt=this,l=pt.l;pt["xs"+ l]+=(pad&&l)?" "+ pfx:pfx||"";if(!c)if(l!==0&&!pt.plugin){pt["xs"+ l]+=s+(sfx||"");return pt;}
pt.l++;pt.type=pt.setRatio?2:1;pt["xs"+ pt.l]=sfx||"";if(l>0){pt.data["xn"+ l]=s+ c;pt.rxp["xn"+ l]=r;pt["xn"+ l]=s;if(!pt.plugin){pt.xfirst=new CSSPropTween(pt,"xn"+ l,s,c,pt.xfirst||pt,0,pt.n,r,pt.pr);pt.xfirst.xs0=0;}
return pt;}
pt.data={s:s+ c};pt.rxp={};pt.s=s;pt.c=c;pt.r=r;return pt;};var SpecialProp=function(p,options){options=options||{};this.p=options.prefix?_checkPropPrefix(p)||p:p;_specialProps[p]=_specialProps[this.p]=this;this.format=options.formatter||_getFormatter(options.defaultValue,options.color,options.collapsible,options.multi);if(options.parser){this.parse=options.parser;}
this.clrs=options.color;this.multi=options.multi;this.keyword=options.keyword;this.dflt=options.defaultValue;this.pr=options.priority||0;},_registerComplexSpecialProp=_internals._registerComplexSpecialProp=function(p,options,defaults){if(typeof(options)!=="object"){options={parser:defaults};}
var a=p.split(","),d=options.defaultValue,i,temp;defaults=defaults||[d];for(i=0;i<a.length;i++){options.prefix=(i===0&&options.prefix);options.defaultValue=defaults[i]||d;temp=new SpecialProp(a[i],options);}},_registerPluginProp=function(p){if(!_specialProps[p]){var pluginName=p.charAt(0).toUpperCase()+ p.substr(1)+"Plugin";_registerComplexSpecialProp(p,{parser:function(t,e,p,cssp,pt,plugin,vars){var pluginClass=(window.GreenSockGlobals||window).com.greensock.plugins[pluginName];if(!pluginClass){_log("Error: "+ pluginName+" js file not loaded.");return pt;}
pluginClass._cssRegister();return _specialProps[p].parse(t,e,p,cssp,pt,plugin,vars);}});}};p=SpecialProp.prototype;p.parseComplex=function(t,b,e,pt,plugin,setRatio){var kwd=this.keyword,i,ba,ea,l,bi,ei;if(this.multi)if(_commasOutsideParenExp.test(e)||_commasOutsideParenExp.test(b)){ba=b.replace(_commasOutsideParenExp,"|").split("|");ea=e.replace(_commasOutsideParenExp,"|").split("|");}else if(kwd){ba=[b];ea=[e];}
if(ea){l=(ea.length>ba.length)?ea.length:ba.length;for(i=0;i<l;i++){b=ba[i]=ba[i]||this.dflt;e=ea[i]=ea[i]||this.dflt;if(kwd){bi=b.indexOf(kwd);ei=e.indexOf(kwd);if(bi!==ei){e=(ei===-1)?ea:ba;e[i]+=" "+ kwd;}}}
b=ba.join(", ");e=ea.join(", ");}
return _parseComplex(t,this.p,b,e,this.clrs,this.dflt,pt,this.pr,plugin,setRatio);};p.parse=function(t,e,p,cssp,pt,plugin,vars){return this.parseComplex(t.style,this.format(_getStyle(t,this.p,_cs,false,this.dflt)),this.format(e),pt,plugin);};CSSPlugin.registerSpecialProp=function(name,onInitTween,priority){_registerComplexSpecialProp(name,{parser:function(t,e,p,cssp,pt,plugin,vars){var rv=new CSSPropTween(t,p,0,0,pt,2,p,false,priority);rv.plugin=plugin;rv.setRatio=onInitTween(t,e,cssp._tween,p);return rv;},priority:priority});};var _transformProps=("scaleX,scaleY,scaleZ,x,y,z,skewX,rotation,rotationX,rotationY,perspective").split(","),_transformProp=_checkPropPrefix("transform"),_transformPropCSS=_prefixCSS+"transform",_transformOriginProp=_checkPropPrefix("transformOrigin"),_supports3D=(_checkPropPrefix("perspective")!==null),_getTransform=function(t,cs,rec,parse){if(t._gsTransform&&rec&&!parse){return t._gsTransform;}
var tm=rec?t._gsTransform||{skewY:0}:{skewY:0},invX=(tm.scaleX<0),min=0.00002,rnd=100000,minAngle=179.99,minPI=minAngle*_DEG2RAD,zOrigin=_supports3D?parseFloat(_getStyle(t,_transformOriginProp,cs,false,"0 0 0").split(" ")[2])||tm.zOrigin||0:0,s,m,i,n,dec,scaleX,scaleY,rotation,skewX,difX,difY,difR,difS;if(_transformProp){s=_getStyle(t,_transformPropCSS,cs,true);}else if(t.currentStyle){s=t.currentStyle.filter.match(_ieGetMatrixExp);s=(s&&s.length===4)?[s[0].substr(4),Number(s[2].substr(4)),Number(s[1].substr(4)),s[3].substr(4),(tm.x||0),(tm.y||0)].join(","):"";}
m=(s||"").match(/(?:\-|\b)[\d\-\.e]+\b/gi)||[];i=m.length;while(--i>-1){n=Number(m[i]);m[i]=(dec=n-(n|=0))?((dec*rnd+(dec<0?-0.5:0.5))|0)/rnd+ n:n;}
if(m.length===16){var a13=m[8],a23=m[9],a33=m[10],a14=m[12],a24=m[13],a34=m[14];if(tm.zOrigin){a34=-tm.zOrigin;a14=a13*a34-m[12];a24=a23*a34-m[13];a34=a33*a34+tm.zOrigin-m[14];}
if(!rec||parse||tm.rotationX==null){var a11=m[0],a21=m[1],a31=m[2],a41=m[3],a12=m[4],a22=m[5],a32=m[6],a42=m[7],a43=m[11],angle=Math.atan2(a32,a33),xFlip=(angle<-minPI||angle>minPI),t1,t2,t3,cos,sin,yFlip,zFlip;tm.rotationX=angle*_RAD2DEG;if(angle){cos=Math.cos(-angle);sin=Math.sin(-angle);t1=a12*cos+a13*sin;t2=a22*cos+a23*sin;t3=a32*cos+a33*sin;a13=a12*-sin+a13*cos;a23=a22*-sin+a23*cos;a33=a32*-sin+a33*cos;a43=a42*-sin+a43*cos;a12=t1;a22=t2;a32=t3;}
angle=Math.atan2(a13,a11);tm.rotationY=angle*_RAD2DEG;if(angle){yFlip=(angle<-minPI||angle>minPI);cos=Math.cos(-angle);sin=Math.sin(-angle);t1=a11*cos-a13*sin;t2=a21*cos-a23*sin;t3=a31*cos-a33*sin;a23=a21*sin+a23*cos;a33=a31*sin+a33*cos;a43=a41*sin+a43*cos;a11=t1;a21=t2;a31=t3;}
angle=Math.atan2(a21,a22);tm.rotation=angle*_RAD2DEG;if(angle){zFlip=(angle<-minPI||angle>minPI);cos=Math.cos(-angle);sin=Math.sin(-angle);a11=a11*cos+a12*sin;t2=a21*cos+a22*sin;a22=a21*-sin+a22*cos;a32=a31*-sin+a32*cos;a21=t2;}
if(zFlip&&xFlip){tm.rotation=tm.rotationX=0;}else if(zFlip&&yFlip){tm.rotation=tm.rotationY=0;}else if(yFlip&&xFlip){tm.rotationY=tm.rotationX=0;}
tm.scaleX=((Math.sqrt(a11*a11+ a21*a21)*rnd+ 0.5)|0)/rnd;tm.scaleY=((Math.sqrt(a22*a22+ a23*a23)*rnd+ 0.5)|0)/rnd;tm.scaleZ=((Math.sqrt(a32*a32+ a33*a33)*rnd+ 0.5)|0)/rnd;tm.skewX=0;tm.perspective=a43?1/((a43<0)?-a43:a43):0;tm.x=a14;tm.y=a24;tm.z=a34;}}else if((!_supports3D||parse||!m.length||tm.x!==m[4]||tm.y!==m[5]||(!tm.rotationX&&!tm.rotationY))&&!(tm.x!==undefined&&_getStyle(t,"display",cs)==="none")){var k=(m.length>=6),a=k?m[0]:1,b=m[1]||0,c=m[2]||0,d=k?m[3]:1;tm.x=m[4]||0;tm.y=m[5]||0;scaleX=Math.sqrt(a*a+ b*b);scaleY=Math.sqrt(d*d+ c*c);rotation=(a||b)?Math.atan2(b,a)*_RAD2DEG:tm.rotation||0;skewX=(c||d)?Math.atan2(c,d)*_RAD2DEG+ rotation:tm.skewX||0;difX=scaleX- Math.abs(tm.scaleX||0);difY=scaleY- Math.abs(tm.scaleY||0);if(Math.abs(skewX)>90&&Math.abs(skewX)<270){if(invX){scaleX*=-1;skewX+=(rotation<=0)?180:-180;rotation+=(rotation<=0)?180:-180;}else{scaleY*=-1;skewX+=(skewX<=0)?180:-180;}}
difR=(rotation- tm.rotation)%180;difS=(skewX- tm.skewX)%180;if(tm.skewX===undefined||difX>min||difX<-min||difY>min||difY<-min||(difR>-minAngle&&difR<minAngle&&(difR*rnd)|0!==0)||(difS>-minAngle&&difS<minAngle&&(difS*rnd)|0!==0)){tm.scaleX=scaleX;tm.scaleY=scaleY;tm.rotation=rotation;tm.skewX=skewX;}
if(_supports3D){tm.rotationX=tm.rotationY=tm.z=0;tm.perspective=parseFloat(CSSPlugin.defaultTransformPerspective)||0;tm.scaleZ=1;}}
tm.zOrigin=zOrigin;for(i in tm){if(tm[i]<min)if(tm[i]>-min){tm[i]=0;}}
if(rec){t._gsTransform=tm;}
return tm;},_setIETransformRatio=function(v){var t=this.data,ang=-t.rotation*_DEG2RAD,skew=ang+ t.skewX*_DEG2RAD,rnd=100000,a=((Math.cos(ang)*t.scaleX*rnd)|0)/rnd,b=((Math.sin(ang)*t.scaleX*rnd)|0)/rnd,c=((Math.sin(skew)*-t.scaleY*rnd)|0)/rnd,d=((Math.cos(skew)*t.scaleY*rnd)|0)/rnd,style=this.t.style,cs=this.t.currentStyle,filters,val;if(!cs){return;}
val=b;b=-c;c=-val;filters=cs.filter;style.filter="";var w=this.t.offsetWidth,h=this.t.offsetHeight,clip=(cs.position!=="absolute"),m="progid:DXImageTransform.Microsoft.Matrix(M11="+ a+", M12="+ b+", M21="+ c+", M22="+ d,ox=t.x,oy=t.y,dx,dy;if(t.ox!=null){dx=((t.oxp)?w*t.ox*0.01:t.ox)- w/2;dy=((t.oyp)?h*t.oy*0.01:t.oy)- h/2;ox+=dx-(dx*a+ dy*b);oy+=dy-(dx*c+ dy*d);}
if(!clip){m+=", sizingMethod='auto expand')";}else{dx=(w/2);dy=(h/2);m+=", Dx="+(dx-(dx*a+ dy*b)+ ox)+", Dy="+(dy-(dx*c+ dy*d)+ oy)+")";}
if(filters.indexOf("DXImageTransform.Microsoft.Matrix(")!==-1){style.filter=filters.replace(_ieSetMatrixExp,m);}else{style.filter=m+" "+ filters;}
if(v===0||v===1)if(a===1)if(b===0)if(c===0)if(d===1)if(!clip||m.indexOf("Dx=0, Dy=0")!==-1)if(!_opacityExp.test(filters)||parseFloat(RegExp.$1)===100)if(filters.indexOf("gradient("&&filters.indexOf("Alpha"))===-1){style.removeAttribute("filter");}
if(!clip){var mult=(_ieVers<8)?1:-1,marg,prop,dif;dx=t.ieOffsetX||0;dy=t.ieOffsetY||0;t.ieOffsetX=Math.round((w-((a<0?-a:a)*w+(b<0?-b:b)*h))/2+ ox);t.ieOffsetY=Math.round((h-((d<0?-d:d)*h+(c<0?-c:c)*w))/2+ oy);for(i=0;i<4;i++){prop=_margins[i];marg=cs[prop];val=(marg.indexOf("px")!==-1)?parseFloat(marg):_convertToPixels(this.t,prop,parseFloat(marg),marg.replace(_suffixExp,""))||0;if(val!==t[prop]){dif=(i<2)?-t.ieOffsetX:-t.ieOffsetY;}else{dif=(i<2)?dx- t.ieOffsetX:dy- t.ieOffsetY;}
style[prop]=(t[prop]=Math.round(val- dif*((i===0||i===2)?1:mult)))+"px";}}},_set3DTransformRatio=function(v){var t=this.data,style=this.t.style,angle=t.rotation*_DEG2RAD,sx=t.scaleX,sy=t.scaleY,sz=t.scaleZ,perspective=t.perspective,a11,a12,a13,a14,a21,a22,a23,a24,a31,a32,a33,a34,a41,a42,a43,zOrigin,rnd,cos,sin,t1,t2,t3,t4;if(_isFirefox){var n=0.0001;if(sx<n&&sx>-n){sx=sz=0.00002;}
if(sy<n&&sy>-n){sy=sz=0.00002;}
if(perspective&&!t.z&&!t.rotationX&&!t.rotationY){perspective=0;}}
if(angle||t.skewX){cos=Math.cos(angle);sin=Math.sin(angle);a11=cos;a21=sin;if(t.skewX){angle-=t.skewX*_DEG2RAD;cos=Math.cos(angle);sin=Math.sin(angle);}
a12=-sin;a22=cos;}else if(!t.rotationY&&!t.rotationX&&sz===1&&!perspective){style[_transformProp]="translate3d("+ t.x+"px,"+ t.y+"px,"+ t.z+"px)"+((sx!==1||sy!==1)?" scale("+ sx+","+ sy+")":"");return;}else{a11=a22=1;a12=a21=0;}
a33=1;a13=a14=a23=a24=a31=a32=a34=a41=a42=0;a43=(perspective)?-1/perspective:0;zOrigin=t.zOrigin;rnd=100000;angle=t.rotationY*_DEG2RAD;if(angle){cos=Math.cos(angle);sin=Math.sin(angle);a31=a33*-sin;a41=a43*-sin;a13=a11*sin;a23=a21*sin;a33*=cos;a43*=cos;a11*=cos;a21*=cos;}
angle=t.rotationX*_DEG2RAD;if(angle){cos=Math.cos(angle);sin=Math.sin(angle);t1=a12*cos+a13*sin;t2=a22*cos+a23*sin;t3=a32*cos+a33*sin;t4=a42*cos+a43*sin;a13=a12*-sin+a13*cos;a23=a22*-sin+a23*cos;a33=a32*-sin+a33*cos;a43=a42*-sin+a43*cos;a12=t1;a22=t2;a32=t3;a42=t4;}
if(sz!==1){a13*=sz;a23*=sz;a33*=sz;a43*=sz;}
if(sy!==1){a12*=sy;a22*=sy;a32*=sy;a42*=sy;}
if(sx!==1){a11*=sx;a21*=sx;a31*=sx;a41*=sx;}
if(zOrigin){a34-=zOrigin;a14=a13*a34;a24=a23*a34;a34=a33*a34+zOrigin;}
a14=(t1=(a14+=t.x)-(a14|=0))?((t1*rnd+(t1<0?-0.5:0.5))|0)/rnd+ a14:a14;a24=(t1=(a24+=t.y)-(a24|=0))?((t1*rnd+(t1<0?-0.5:0.5))|0)/rnd+ a24:a24;a34=(t1=(a34+=t.z)-(a34|=0))?((t1*rnd+(t1<0?-0.5:0.5))|0)/rnd+ a34:a34;style[_transformProp]="matrix3d("+[(((a11*rnd)|0)/rnd),(((a21*rnd)|0)/rnd),(((a31*rnd)|0)/rnd),(((a41*rnd)|0)/rnd),(((a12*rnd)|0)/rnd),(((a22*rnd)|0)/rnd),(((a32*rnd)|0)/rnd),(((a42*rnd)|0)/rnd),(((a13*rnd)|0)/rnd),(((a23*rnd)|0)/rnd),(((a33*rnd)|0)/rnd),(((a43*rnd)|0)/rnd),a14,a24,a34,(perspective?(1+(-a34/perspective)):1)].join(",")+")";},_set2DTransformRatio=function(v){var t=this.data,targ=this.t,style=targ.style,ang,skew,rnd,sx,sy;if(t.rotationX||t.rotationY||t.z||t.force3D){this.setRatio=_set3DTransformRatio;_set3DTransformRatio.call(this,v);return;}
if(!t.rotation&&!t.skewX){style[_transformProp]="matrix("+ t.scaleX+",0,0,"+ t.scaleY+","+ t.x+","+ t.y+")";}else{ang=t.rotation*_DEG2RAD;skew=ang- t.skewX*_DEG2RAD;rnd=100000;sx=t.scaleX*rnd;sy=t.scaleY*rnd;style[_transformProp]="matrix("+(((Math.cos(ang)*sx)|0)/rnd)+","+(((Math.sin(ang)*sx)|0)/rnd)+","+(((Math.sin(skew)*-sy)|0)/rnd)+","+(((Math.cos(skew)*sy)|0)/rnd)+","+ t.x+","+ t.y+")";}};_registerComplexSpecialProp("transform,scale,scaleX,scaleY,scaleZ,x,y,z,rotation,rotationX,rotationY,rotationZ,skewX,skewY,shortRotation,shortRotationX,shortRotationY,shortRotationZ,transformOrigin,transformPerspective,directionalRotation,parseTransform,force3D",{parser:function(t,e,p,cssp,pt,plugin,vars){if(cssp._transform){return pt;}
var m1=cssp._transform=_getTransform(t,_cs,true,vars.parseTransform),style=t.style,min=0.000001,i=_transformProps.length,v=vars,endRotations={},m2,skewY,copy,orig,has3D,hasChange,dr;if(typeof(v.transform)==="string"&&_transformProp){copy=style.cssText;style[_transformProp]=v.transform;style.display="block";m2=_getTransform(t,null,false);style.cssText=copy;}else if(typeof(v)==="object"){m2={scaleX:_parseVal((v.scaleX!=null)?v.scaleX:v.scale,m1.scaleX),scaleY:_parseVal((v.scaleY!=null)?v.scaleY:v.scale,m1.scaleY),scaleZ:_parseVal(v.scaleZ,m1.scaleZ),x:_parseVal(v.x,m1.x),y:_parseVal(v.y,m1.y),z:_parseVal(v.z,m1.z),perspective:_parseVal(v.transformPerspective,m1.perspective)};dr=v.directionalRotation;if(dr!=null){if(typeof(dr)==="object"){for(copy in dr){v[copy]=dr[copy];}}else{v.rotation=dr;}}
m2.rotation=_parseAngle(("rotation"in v)?v.rotation:("shortRotation"in v)?v.shortRotation+"_short":("rotationZ"in v)?v.rotationZ:m1.rotation,m1.rotation,"rotation",endRotations);if(_supports3D){m2.rotationX=_parseAngle(("rotationX"in v)?v.rotationX:("shortRotationX"in v)?v.shortRotationX+"_short":m1.rotationX||0,m1.rotationX,"rotationX",endRotations);m2.rotationY=_parseAngle(("rotationY"in v)?v.rotationY:("shortRotationY"in v)?v.shortRotationY+"_short":m1.rotationY||0,m1.rotationY,"rotationY",endRotations);}
m2.skewX=(v.skewX==null)?m1.skewX:_parseAngle(v.skewX,m1.skewX);m2.skewY=(v.skewY==null)?m1.skewY:_parseAngle(v.skewY,m1.skewY);if((skewY=m2.skewY- m1.skewY)){m2.skewX+=skewY;m2.rotation+=skewY;}}
if(_supports3D&&v.force3D!=null){m1.force3D=v.force3D;hasChange=true;}
has3D=(m1.force3D||m1.z||m1.rotationX||m1.rotationY||m2.z||m2.rotationX||m2.rotationY||m2.perspective);if(!has3D&&v.scale!=null){m2.scaleZ=1;}
while(--i>-1){p=_transformProps[i];orig=m2[p]- m1[p];if(orig>min||orig<-min||_forcePT[p]!=null){hasChange=true;pt=new CSSPropTween(m1,p,m1[p],orig,pt);if(p in endRotations){pt.e=endRotations[p];}
pt.xs0=0;pt.plugin=plugin;cssp._overwriteProps.push(pt.n);}}
orig=v.transformOrigin;if(orig||(_supports3D&&has3D&&m1.zOrigin)){if(_transformProp){hasChange=true;p=_transformOriginProp;orig=(orig||_getStyle(t,p,_cs,false,"50% 50%"))+"";pt=new CSSPropTween(style,p,0,0,pt,-1,"transformOrigin");pt.b=style[p];pt.plugin=plugin;if(_supports3D){copy=m1.zOrigin;orig=orig.split(" ");m1.zOrigin=((orig.length>2&&!(copy!==0&&orig[2]==="0px"))?parseFloat(orig[2]):copy)||0;pt.xs0=pt.e=style[p]=orig[0]+" "+(orig[1]||"50%")+" 0px";pt=new CSSPropTween(m1,"zOrigin",0,0,pt,-1,pt.n);pt.b=copy;pt.xs0=pt.e=m1.zOrigin;}else{pt.xs0=pt.e=style[p]=orig;}}else{_parsePosition(orig+"",m1);}}
if(hasChange){cssp._transformType=(has3D||this._transformType===3)?3:2;}
return pt;},prefix:true});_registerComplexSpecialProp("boxShadow",{defaultValue:"0px 0px 0px 0px #999",prefix:true,color:true,multi:true,keyword:"inset"});_registerComplexSpecialProp("borderRadius",{defaultValue:"0px",parser:function(t,e,p,cssp,pt,plugin){e=this.format(e);var props=["borderTopLeftRadius","borderTopRightRadius","borderBottomRightRadius","borderBottomLeftRadius"],style=t.style,ea1,i,es2,bs2,bs,es,bn,en,w,h,esfx,bsfx,rel,hn,vn,em;w=parseFloat(t.offsetWidth);h=parseFloat(t.offsetHeight);ea1=e.split(" ");for(i=0;i<props.length;i++){if(this.p.indexOf("border")){props[i]=_checkPropPrefix(props[i]);}
bs=bs2=_getStyle(t,props[i],_cs,false,"0px");if(bs.indexOf(" ")!==-1){bs2=bs.split(" ");bs=bs2[0];bs2=bs2[1];}
es=es2=ea1[i];bn=parseFloat(bs);bsfx=bs.substr((bn+"").length);rel=(es.charAt(1)==="=");if(rel){en=parseInt(es.charAt(0)+"1",10);es=es.substr(2);en*=parseFloat(es);esfx=es.substr((en+"").length-(en<0?1:0))||"";}else{en=parseFloat(es);esfx=es.substr((en+"").length);}
if(esfx===""){esfx=_suffixMap[p]||bsfx;}
if(esfx!==bsfx){hn=_convertToPixels(t,"borderLeft",bn,bsfx);vn=_convertToPixels(t,"borderTop",bn,bsfx);if(esfx==="%"){bs=(hn/w*100)+"%";bs2=(vn/h*100)+"%";}else if(esfx==="em"){em=_convertToPixels(t,"borderLeft",1,"em");bs=(hn/em)+"em";bs2=(vn/em)+"em";}else{bs=hn+"px";bs2=vn+"px";}
if(rel){es=(parseFloat(bs)+ en)+ esfx;es2=(parseFloat(bs2)+ en)+ esfx;}}
pt=_parseComplex(style,props[i],bs+" "+ bs2,es+" "+ es2,false,"0px",pt);}
return pt;},prefix:true,formatter:_getFormatter("0px 0px 0px 0px",false,true)});_registerComplexSpecialProp("backgroundPosition",{defaultValue:"0 0",parser:function(t,e,p,cssp,pt,plugin){var bp="background-position",cs=(_cs||_getComputedStyle(t,null)),bs=this.format(((cs)?_ieVers?cs.getPropertyValue(bp+"-x")+" "+ cs.getPropertyValue(bp+"-y"):cs.getPropertyValue(bp):t.currentStyle.backgroundPositionX+" "+ t.currentStyle.backgroundPositionY)||"0 0"),es=this.format(e),ba,ea,i,pct,overlap,src;if((bs.indexOf("%")!==-1)!==(es.indexOf("%")!==-1)){src=_getStyle(t,"backgroundImage").replace(_urlExp,"");if(src&&src!=="none"){ba=bs.split(" ");ea=es.split(" ");_tempImg.setAttribute("src",src);i=2;while(--i>-1){bs=ba[i];pct=(bs.indexOf("%")!==-1);if(pct!==(ea[i].indexOf("%")!==-1)){overlap=(i===0)?t.offsetWidth- _tempImg.width:t.offsetHeight- _tempImg.height;ba[i]=pct?(parseFloat(bs)/100*overlap)+"px":(parseFloat(bs)/overlap*100)+"%";}}
bs=ba.join(" ");}}
return this.parseComplex(t.style,bs,es,pt,plugin);},formatter:_parsePosition});_registerComplexSpecialProp("backgroundSize",{defaultValue:"0 0",formatter:_parsePosition});_registerComplexSpecialProp("perspective",{defaultValue:"0px",prefix:true});_registerComplexSpecialProp("perspectiveOrigin",{defaultValue:"50% 50%",prefix:true});_registerComplexSpecialProp("transformStyle",{prefix:true});_registerComplexSpecialProp("backfaceVisibility",{prefix:true});_registerComplexSpecialProp("userSelect",{prefix:true});_registerComplexSpecialProp("margin",{parser:_getEdgeParser("marginTop,marginRight,marginBottom,marginLeft")});_registerComplexSpecialProp("padding",{parser:_getEdgeParser("paddingTop,paddingRight,paddingBottom,paddingLeft")});_registerComplexSpecialProp("clip",{defaultValue:"rect(0px,0px,0px,0px)",parser:function(t,e,p,cssp,pt,plugin){var b,cs,delim;if(_ieVers<9){cs=t.currentStyle;delim=_ieVers<8?" ":",";b="rect("+ cs.clipTop+ delim+ cs.clipRight+ delim+ cs.clipBottom+ delim+ cs.clipLeft+")";e=this.format(e).split(",").join(delim);}else{b=this.format(_getStyle(t,this.p,_cs,false,this.dflt));e=this.format(e);}
return this.parseComplex(t.style,b,e,pt,plugin);}});_registerComplexSpecialProp("textShadow",{defaultValue:"0px 0px 0px #999",color:true,multi:true});_registerComplexSpecialProp("autoRound,strictUnits",{parser:function(t,e,p,cssp,pt){return pt;}});_registerComplexSpecialProp("border",{defaultValue:"0px solid #000",parser:function(t,e,p,cssp,pt,plugin){return this.parseComplex(t.style,this.format(_getStyle(t,"borderTopWidth",_cs,false,"0px")+" "+ _getStyle(t,"borderTopStyle",_cs,false,"solid")+" "+ _getStyle(t,"borderTopColor",_cs,false,"#000")),this.format(e),pt,plugin);},color:true,formatter:function(v){var a=v.split(" ");return a[0]+" "+(a[1]||"solid")+" "+(v.match(_colorExp)||["#000"])[0];}});_registerComplexSpecialProp("borderWidth",{parser:_getEdgeParser("borderTopWidth,borderRightWidth,borderBottomWidth,borderLeftWidth")});_registerComplexSpecialProp("float,cssFloat,styleFloat",{parser:function(t,e,p,cssp,pt,plugin){var s=t.style,prop=("cssFloat"in s)?"cssFloat":"styleFloat";return new CSSPropTween(s,prop,0,0,pt,-1,p,false,0,s[prop],e);}});var _setIEOpacityRatio=function(v){var t=this.t,filters=t.filter||_getStyle(this.data,"filter"),val=(this.s+ this.c*v)|0,skip;if(val===100){if(filters.indexOf("atrix(")===-1&&filters.indexOf("radient(")===-1&&filters.indexOf("oader(")===-1){t.removeAttribute("filter");skip=(!_getStyle(this.data,"filter"));}else{t.filter=filters.replace(_alphaFilterExp,"");skip=true;}}
if(!skip){if(this.xn1){t.filter=filters=filters||("alpha(opacity="+ val+")");}
if(filters.indexOf("opacity")===-1){if(val!==0||!this.xn1){t.filter=filters+" alpha(opacity="+ val+")";}}else{t.filter=filters.replace(_opacityExp,"opacity="+ val);}}};_registerComplexSpecialProp("opacity,alpha,autoAlpha",{defaultValue:"1",parser:function(t,e,p,cssp,pt,plugin){var b=parseFloat(_getStyle(t,"opacity",_cs,false,"1")),style=t.style,isAutoAlpha=(p==="autoAlpha");if(typeof(e)==="string"&&e.charAt(1)==="="){e=((e.charAt(0)==="-")?-1:1)*parseFloat(e.substr(2))+ b;}
if(isAutoAlpha&&b===1&&_getStyle(t,"visibility",_cs)==="hidden"&&e!==0){b=0;}
if(_supportsOpacity){pt=new CSSPropTween(style,"opacity",b,e- b,pt);}else{pt=new CSSPropTween(style,"opacity",b*100,(e- b)*100,pt);pt.xn1=isAutoAlpha?1:0;style.zoom=1;pt.type=2;pt.b="alpha(opacity="+ pt.s+")";pt.e="alpha(opacity="+(pt.s+ pt.c)+")";pt.data=t;pt.plugin=plugin;pt.setRatio=_setIEOpacityRatio;}
if(isAutoAlpha){pt=new CSSPropTween(style,"visibility",0,0,pt,-1,null,false,0,((b!==0)?"inherit":"hidden"),((e===0)?"hidden":"inherit"));pt.xs0="inherit";cssp._overwriteProps.push(pt.n);cssp._overwriteProps.push(p);}
return pt;}});var _removeProp=function(s,p){if(p){if(s.removeProperty){s.removeProperty(p.replace(_capsExp,"-$1").toLowerCase());}else{s.removeAttribute(p);}}},_setClassNameRatio=function(v){this.t._gsClassPT=this;if(v===1||v===0){this.t.className=(v===0)?this.b:this.e;var mpt=this.data,s=this.t.style;while(mpt){if(!mpt.v){_removeProp(s,mpt.p);}else{s[mpt.p]=mpt.v;}
mpt=mpt._next;}
if(v===1&&this.t._gsClassPT===this){this.t._gsClassPT=null;}}else if(this.t.className!==this.e){this.t.className=this.e;}};_registerComplexSpecialProp("className",{parser:function(t,e,p,cssp,pt,plugin,vars){var b=t.className,cssText=t.style.cssText,difData,bs,cnpt,cnptLookup,mpt;pt=cssp._classNamePT=new CSSPropTween(t,p,0,0,pt,2);pt.setRatio=_setClassNameRatio;pt.pr=-11;_hasPriority=true;pt.b=b;bs=_getAllStyles(t,_cs);cnpt=t._gsClassPT;if(cnpt){cnptLookup={};mpt=cnpt.data;while(mpt){cnptLookup[mpt.p]=1;mpt=mpt._next;}
cnpt.setRatio(1);}
t._gsClassPT=pt;pt.e=(e.charAt(1)!=="=")?e:b.replace(new RegExp("\\s*\\b"+ e.substr(2)+"\\b"),"")+((e.charAt(0)==="+")?" "+ e.substr(2):"");if(cssp._tween._duration){t.className=pt.e;difData=_cssDif(t,bs,_getAllStyles(t),vars,cnptLookup);t.className=b;pt.data=difData.firstMPT;t.style.cssText=cssText;pt=pt.xfirst=cssp.parse(t,difData.difs,pt,plugin);}
return pt;}});var _setClearPropsRatio=function(v){if(v===1||v===0)if(this.data._totalTime===this.data._totalDuration&&this.data.data!=="isFromStart"){var s=this.t.style,transformParse=_specialProps.transform.parse,a,p,i,clearTransform;if(this.e==="all"){s.cssText="";clearTransform=true;}else{a=this.e.split(",");i=a.length;while(--i>-1){p=a[i];if(_specialProps[p]){if(_specialProps[p].parse===transformParse){clearTransform=true;}else{p=(p==="transformOrigin")?_transformOriginProp:_specialProps[p].p;}}
_removeProp(s,p);}}
if(clearTransform){_removeProp(s,_transformProp);if(this.t._gsTransform){delete this.t._gsTransform;}}}};_registerComplexSpecialProp("clearProps",{parser:function(t,e,p,cssp,pt){pt=new CSSPropTween(t,p,0,0,pt,2);pt.setRatio=_setClearPropsRatio;pt.e=e;pt.pr=-10;pt.data=cssp._tween;_hasPriority=true;return pt;}});p="bezier,throwProps,physicsProps,physics2D".split(",");i=p.length;while(i--){_registerPluginProp(p[i]);}
p=CSSPlugin.prototype;p._firstPT=null;p._onInitTween=function(target,vars,tween){if(!target.nodeType){return false;}
this._target=target;this._tween=tween;this._vars=vars;_autoRound=vars.autoRound;_hasPriority=false;_suffixMap=vars.suffixMap||CSSPlugin.suffixMap;_cs=_getComputedStyle(target,"");_overwriteProps=this._overwriteProps;var style=target.style,v,pt,pt2,first,last,next,zIndex,tpt,threeD;if(_reqSafariFix)if(style.zIndex===""){v=_getStyle(target,"zIndex",_cs);if(v==="auto"||v===""){style.zIndex=0;}}
if(typeof(vars)==="string"){first=style.cssText;v=_getAllStyles(target,_cs);style.cssText=first+";"+ vars;v=_cssDif(target,v,_getAllStyles(target)).difs;if(!_supportsOpacity&&_opacityValExp.test(vars)){v.opacity=parseFloat(RegExp.$1);}
vars=v;style.cssText=first;}
this._firstPT=pt=this.parse(target,vars,null);if(this._transformType){threeD=(this._transformType===3);if(!_transformProp){style.zoom=1;}else if(_isSafari){_reqSafariFix=true;if(style.zIndex===""){zIndex=_getStyle(target,"zIndex",_cs);if(zIndex==="auto"||zIndex===""){style.zIndex=0;}}
if(_isSafariLT6){style.WebkitBackfaceVisibility=this._vars.WebkitBackfaceVisibility||(threeD?"visible":"hidden");}}
pt2=pt;while(pt2&&pt2._next){pt2=pt2._next;}
tpt=new CSSPropTween(target,"transform",0,0,null,2);this._linkCSSP(tpt,null,pt2);tpt.setRatio=(threeD&&_supports3D)?_set3DTransformRatio:_transformProp?_set2DTransformRatio:_setIETransformRatio;tpt.data=this._transform||_getTransform(target,_cs,true);_overwriteProps.pop();}
if(_hasPriority){while(pt){next=pt._next;pt2=first;while(pt2&&pt2.pr>pt.pr){pt2=pt2._next;}
if((pt._prev=pt2?pt2._prev:last)){pt._prev._next=pt;}else{first=pt;}
if((pt._next=pt2)){pt2._prev=pt;}else{last=pt;}
pt=next;}
this._firstPT=first;}
return true;};p.parse=function(target,vars,pt,plugin){var style=target.style,p,sp,bn,en,bs,es,bsfx,esfx,isStr,rel;for(p in vars){es=vars[p];sp=_specialProps[p];if(sp){pt=sp.parse(target,es,p,this,pt,plugin,vars);}else{bs=_getStyle(target,p,_cs)+"";isStr=(typeof(es)==="string");if(p==="color"||p==="fill"||p==="stroke"||p.indexOf("Color")!==-1||(isStr&&_rgbhslExp.test(es))){if(!isStr){es=_parseColor(es);es=((es.length>3)?"rgba(":"rgb(")+ es.join(",")+")";}
pt=_parseComplex(style,p,bs,es,true,"transparent",pt,0,plugin);}else if(isStr&&(es.indexOf(" ")!==-1||es.indexOf(",")!==-1)){pt=_parseComplex(style,p,bs,es,true,null,pt,0,plugin);}else{bn=parseFloat(bs);bsfx=(bn||bn===0)?bs.substr((bn+"").length):"";if(bs===""||bs==="auto"){if(p==="width"||p==="height"){bn=_getDimension(target,p,_cs);bsfx="px";}else if(p==="left"||p==="top"){bn=_calculateOffset(target,p,_cs);bsfx="px";}else{bn=(p!=="opacity")?0:1;bsfx="";}}
rel=(isStr&&es.charAt(1)==="=");if(rel){en=parseInt(es.charAt(0)+"1",10);es=es.substr(2);en*=parseFloat(es);esfx=es.replace(_suffixExp,"");}else{en=parseFloat(es);esfx=isStr?es.substr((en+"").length)||"":"";}
if(esfx===""){esfx=(p in _suffixMap)?_suffixMap[p]:bsfx;}
es=(en||en===0)?(rel?en+ bn:en)+ esfx:vars[p];if(bsfx!==esfx)if(esfx!=="")if(en||en===0)if(bn||bn===0){bn=_convertToPixels(target,p,bn,bsfx);if(esfx==="%"){bn/=_convertToPixels(target,p,100,"%")/100;if(vars.strictUnits!==true){bs=bn+"%";}}else if(esfx==="em"){bn/=_convertToPixels(target,p,1,"em");}else{en=_convertToPixels(target,p,en,esfx);esfx="px";}
if(rel)if(en||en===0){es=(en+ bn)+ esfx;}}
if(rel){en+=bn;}
if((bn||bn===0)&&(en||en===0)){pt=new CSSPropTween(style,p,bn,en- bn,pt,0,p,(_autoRound!==false&&(esfx==="px"||p==="zIndex")),0,bs,es);pt.xs0=esfx;}else if(style[p]===undefined||!es&&(es+""==="NaN"||es==null)){_log("invalid "+ p+" tween value: "+ vars[p]);}else{pt=new CSSPropTween(style,p,en||bn||0,0,pt,-1,p,false,0,bs,es);pt.xs0=(es==="none"&&(p==="display"||p.indexOf("Style")!==-1))?bs:es;}}}
if(plugin)if(pt&&!pt.plugin){pt.plugin=plugin;}}
return pt;};p.setRatio=function(v){var pt=this._firstPT,min=0.000001,val,str,i;if(v===1&&(this._tween._time===this._tween._duration||this._tween._time===0)){while(pt){if(pt.type!==2){pt.t[pt.p]=pt.e;}else{pt.setRatio(v);}
pt=pt._next;}}else if(v||!(this._tween._time===this._tween._duration||this._tween._time===0)||this._tween._rawPrevTime===-0.000001){while(pt){val=pt.c*v+ pt.s;if(pt.r){val=(val>0)?(val+ 0.5)|0:(val- 0.5)|0;}else if(val<min)if(val>-min){val=0;}
if(!pt.type){pt.t[pt.p]=val+ pt.xs0;}else if(pt.type===1){i=pt.l;if(i===2){pt.t[pt.p]=pt.xs0+ val+ pt.xs1+ pt.xn1+ pt.xs2;}else if(i===3){pt.t[pt.p]=pt.xs0+ val+ pt.xs1+ pt.xn1+ pt.xs2+ pt.xn2+ pt.xs3;}else if(i===4){pt.t[pt.p]=pt.xs0+ val+ pt.xs1+ pt.xn1+ pt.xs2+ pt.xn2+ pt.xs3+ pt.xn3+ pt.xs4;}else if(i===5){pt.t[pt.p]=pt.xs0+ val+ pt.xs1+ pt.xn1+ pt.xs2+ pt.xn2+ pt.xs3+ pt.xn3+ pt.xs4+ pt.xn4+ pt.xs5;}else{str=pt.xs0+ val+ pt.xs1;for(i=1;i<pt.l;i++){str+=pt["xn"+i]+ pt["xs"+(i+1)];}
pt.t[pt.p]=str;}}else if(pt.type===-1){pt.t[pt.p]=pt.xs0;}else if(pt.setRatio){pt.setRatio(v);}
pt=pt._next;}}else{while(pt){if(pt.type!==2){pt.t[pt.p]=pt.b;}else{pt.setRatio(v);}
pt=pt._next;}}};p._enableTransforms=function(threeD){this._transformType=(threeD||this._transformType===3)?3:2;this._transform=this._transform||_getTransform(this._target,_cs,true);};p._linkCSSP=function(pt,next,prev,remove){if(pt){if(next){next._prev=pt;}
if(pt._next){pt._next._prev=pt._prev;}
if(pt._prev){pt._prev._next=pt._next;}else if(this._firstPT===pt){this._firstPT=pt._next;remove=true;}
if(prev){prev._next=pt;}else if(!remove&&this._firstPT===null){this._firstPT=pt;}
pt._next=next;pt._prev=prev;}
return pt;};p._kill=function(lookup){var copy=lookup,pt,p,xfirst;if(lookup.autoAlpha||lookup.alpha){copy={};for(p in lookup){copy[p]=lookup[p];}
copy.opacity=1;if(copy.autoAlpha){copy.visibility=1;}}
if(lookup.className&&(pt=this._classNamePT)){xfirst=pt.xfirst;if(xfirst&&xfirst._prev){this._linkCSSP(xfirst._prev,pt._next,xfirst._prev._prev);}else if(xfirst===this._firstPT){this._firstPT=pt._next;}
if(pt._next){this._linkCSSP(pt._next,pt._next._next,xfirst._prev);}
this._classNamePT=null;}
return TweenPlugin.prototype._kill.call(this,copy);};var _getChildStyles=function(e,props,targets){var children,i,child,type;if(e.slice){i=e.length;while(--i>-1){_getChildStyles(e[i],props,targets);}
return;}
children=e.childNodes;i=children.length;while(--i>-1){child=children[i];type=child.type;if(child.style){props.push(_getAllStyles(child));if(targets){targets.push(child);}}
if((type===1||type===9||type===11)&&child.childNodes.length){_getChildStyles(child,props,targets);}}};CSSPlugin.cascadeTo=function(target,duration,vars){var tween=TweenLite.to(target,duration,vars),results=[tween],b=[],e=[],targets=[],_reservedProps=TweenLite._internals.reservedProps,i,difs,p;target=tween._targets||tween.target;_getChildStyles(target,b,targets);tween.render(duration,true);_getChildStyles(target,e);tween.render(0,true);tween._enabled(true);i=targets.length;while(--i>-1){difs=_cssDif(targets[i],b[i],e[i]);if(difs.firstMPT){difs=difs.difs;for(p in vars){if(_reservedProps[p]){difs[p]=vars[p];}}
results.push(TweenLite.to(targets[i],duration,difs));}}
return results;};TweenPlugin.activate([CSSPlugin]);return CSSPlugin;},true);});if(window._gsDefine){window._gsQueue.pop()();}