(window._gsQueue||(window._gsQueue=[])).push(function(){"use strict";var _NaNExp=/[^\d\-\.]/g,_DEG2RAD=Math.PI/180,_numExp=/(\d|\.)+/g,_colorLookup={aqua:[0,255,255],lime:[0,255,0],silver:[192,192,192],black:[0,0,0],maroon:[128,0,0],teal:[0,128,128],blue:[0,0,255],navy:[0,0,128],white:[255,255,255],fuchsia:[255,0,255],olive:[128,128,0],yellow:[255,255,0],orange:[255,165,0],gray:[128,128,128],purple:[128,0,128],green:[0,128,0],red:[255,0,0],pink:[255,192,203],cyan:[0,255,255],transparent:[255,255,255,0]},_parseColor=function(color){if(typeof(color)==="number"){return[color>>16,(color>>8)&255,color&255];}else if(color===""||color==null||color==="none"||typeof(color)!=="string"){return _colorLookup.transparent;}else if(_colorLookup[color]){return _colorLookup[color];}else if(color.charAt(0)==="#"){if(color.length===4){color="#"+ color.charAt(1)+ color.charAt(1)+ color.charAt(2)+ color.charAt(2)+ color.charAt(3)+ color.charAt(3);}
color=parseInt(color.substr(1),16);return[color>>16,(color>>8)&255,color&255];}
return color.match(_numExp)||_colorLookup.transparent;},_transformMap={scaleX:1,scaleY:1,tx:1,ty:1,rotation:1,shortRotation:1,skewX:1,skewY:1,scale:1},_getTransform=function(t,rec){var s=t.matrix,min=0.000001,a=s.a,b=s.b,c=s.c,d=s.d,m=rec?t._gsTransform||{skewY:0}:{skewY:0},invX=(m.scaleX<0);m.tx=s.e-(m.ox||0);m.ty=s.f-(m.oy||0);m.scaleX=Math.sqrt(a*a+ b*b);m.scaleY=Math.sqrt(d*d+ c*c);m.rotation=(a||b)?Math.atan2(b,a):m.rotation||0;m.skewX=(c||d)?Math.atan2(c,d)+ m.rotation:m.skewX||0;if(Math.abs(m.skewX)>Math.PI/2){if(invX){m.scaleX*=-1;m.skewX+=(m.rotation<=0)?Math.PI:-Math.PI;m.rotation+=(m.rotation<=0)?Math.PI:-Math.PI;}else{m.scaleY*=-1;m.skewX+=(m.skewX<=0)?Math.PI:-Math.PI;}}
if(m.rotation<min)if(m.rotation>-min)if(a||b){m.rotation=0;}
if(m.skewX<min)if(m.skewX>-min)if(b||c){m.skewX=0;}
if(rec){t._gsTransform=m;}
return m;},_parseVal=function(v,d){return(v==null)?d:(typeof(v)==="string"&&v.indexOf("=")===1)?parseInt(v.charAt(0)+"1",10)*Number(v.substr(2))+ d:Number(v);},_parseAngle=function(v,d){var m=(v.indexOf("rad")===-1)?_DEG2RAD:1,r=(v.indexOf("=")===1);v=Number(v.replace(_NaNExp,""))*m;return r?v+ d:v;},RaphaelPlugin=window._gsDefine.plugin({propName:"raphael",API:2,init:function(target,value,tween){if(!target.attr){return false;}
this._target=target;this._tween=tween;this._props=target._gsProps=target._gsProps||{};var p,s,v,pt,clr1,clr2,rel;for(p in value){v=value[p];if(p==="transform"){this._parseTransform(target,v);continue;}else if(_transformMap[p]||p==="pivot"){this._parseTransform(target,value);continue;}
s=target.attr(p);this._firstPT=pt={_next:this._firstPT,t:this._props,p:p,b:s,f:false,n:"raphael_"+ p,r:false,type:0};if(p==="fill"||p==="stroke"){clr1=_parseColor(s);clr2=_parseColor(v);pt.e=v;pt.s=Number(clr1[0]);pt.c=Number(clr2[0])- pt.s;pt.gs=Number(clr1[1]);pt.gc=Number(clr2[1])- pt.gs;pt.bs=Number(clr1[2]);pt.bc=Number(clr2[2])- pt.bs;if(clr1.length>3||clr2.length>3){pt.as=(clr1.length<4)?1:Number(clr1[3]);pt.ac=((clr2.length<4)?1:Number(clr2[3]))- pt.as;pt.type=2;}else{pt.type=1;}}else{s=(typeof(s)==="string")?parseFloat(s.replace(_NaNExp,"")):Number(s);if(typeof(v)==="string"){rel=(v.charAt(1)==="=");v=parseFloat(v.replace(_NaNExp,""));}else{rel=false;}
pt.e=(v||v===0)?(rel?v+ s:v):value[p];if((s||s===0)&&(v||v===0)&&(pt.c=(rel?v:v- s))){pt.s=s;}else{pt.type=-1;pt.i=value[p];pt.s=pt.c=0;}}
this._overwriteProps.push("raphael_"+ p);if(pt._next){pt._next._prev=pt;}}
return true;},set:function(v){var pt=this._firstPT,val;while(pt){val=pt.c*v+ pt.s;if(pt.r){val=(val>0)?(val+ 0.5)>>0:(val- 0.5)>>0;}
if(!pt.type){pt.t[pt.p]=val;}else if(pt.type===1){pt.t[pt.p]="rgb("+(val>>0)+", "+((pt.gs+(v*pt.gc))>>0)+", "+((pt.bs+(v*pt.bc))>>0)+")";}else if(pt.type===2){pt.t[pt.p]="rgba("+(val>>0)+", "+((pt.gs+(v*pt.gc))>>0)+", "+((pt.bs+(v*pt.bc))>>0)+", "+(pt.as+(v*pt.ac))+")";}else if(pt.type===-1){pt.t[pt.p]=pt.i;}
pt=pt._next;}
this._target.attr(this._props);if(this._transform){pt=this._transform;var ang=pt.rotation,skew=ang- pt.skewX,a=Math.cos(ang)*pt.scaleX,b=Math.sin(ang)*pt.scaleX,c=Math.sin(skew)*-pt.scaleY,d=Math.cos(skew)*pt.scaleY,min=0.000001,pxl=this._pxl,pyl=this._pyl;if(b<min)if(b>-min){b=0;}
if(c<min)if(c>-min){c=0;}
pt.ox=this._pxg-(pxl*a+ pyl*c);pt.oy=this._pyg-(pxl*b+ pyl*d);this._target.transform("m"+ a+","+ b+","+ c+","+ d+","+(pt.tx+ pt.ox)+","+(pt.ty+ pt.oy));}}}),p=RaphaelPlugin.prototype;p._parseTransform=function(t,v){if(this._transform){return;}
var m1=this._transform=_getTransform(t,true),min=0.000001,m2,skewY,p,pt,copy,dx,dy,mtx,pivot;if(typeof(v)==="object"){m2={scaleX:_parseVal((v.scaleX!=null)?v.scaleX:v.scale,m1.scaleX),scaleY:_parseVal((v.scaleY!=null)?v.scaleY:v.scale,m1.scaleY),tx:_parseVal(v.tx,m1.tx),ty:_parseVal(v.ty,m1.ty)};if(v.shortRotation!=null){m2.rotation=(typeof(v.shortRotation)==="number")?v.shortRotation*_DEG2RAD:_parseAngle(v.shortRotation,m1.rotation);var dif=(m2.rotation- m1.rotation)%(Math.PI*2);if(dif!==dif%Math.PI){dif+=Math.PI*((dif<0)?2:-2);}
m2.rotation=m1.rotation+ dif;}else{m2.rotation=(v.rotation==null)?m1.rotation:(typeof(v.rotation)==="number")?v.rotation*_DEG2RAD:_parseAngle(v.rotation,m1.rotation);}
m2.skewX=(v.skewX==null)?m1.skewX:(typeof(v.skewX)==="number")?v.skewX*_DEG2RAD:_parseAngle(v.skewX,m1.skewX);m2.skewY=(v.skewY==null)?m1.skewY:(typeof(v.skewY)==="number")?v.skewY*_DEG2RAD:_parseAngle(v.skewY,m1.skewY);if((skewY=m2.skewY- m1.skewY)){m2.skewX+=skewY;m2.rotation+=skewY;}
if(m2.skewY<min)if(m2.skewY>-min){m2.skewY=0;}
if(m2.skewX<min)if(m2.skewX>-min){m2.skewX=0;}
if(m2.rotation<min)if(m2.rotation>-min){m2.rotation=0;}
pivot=v.localPivot||v.globalPivot;if(typeof(pivot)==="string"){copy=pivot.split(",");dx=Number(copy[0]);dy=Number(copy[1]);}else if(typeof(pivot)==="object"){dx=Number(pivot.x);dy=Number(pivot.y);}else if(v.localPivot){copy=t.getBBox(true);dx=copy.width/2;dy=copy.height/2;}else{copy=t.getBBox();dx=copy.x+ copy.width/2;dy=copy.y+ copy.height/2;}
if(v.localPivot){mtx=t.matrix;dx+=t.attr("x");dy+=t.attr("y");this._pxl=dx;this._pyl=dy;this._pxg=dx*mtx.a+ dy*mtx.c+ mtx.e- m1.tx;this._pyg=dx*mtx.b+ dy*mtx.d+ mtx.f- m1.ty;}else{mtx=t.matrix.invert();this._pxl=dx*mtx.a+ dy*mtx.c+ mtx.e;this._pyl=dx*mtx.b+ dy*mtx.d+ mtx.f;this._pxg=dx- m1.tx;this._pyg=dy- m1.ty;}}else if(typeof(v)==="string"){copy=this._target.transform();t.transform(v);m2=_getTransform(t,false);t.transform(copy);}else{return;}
for(p in _transformMap){if(m1[p]!==m2[p])if(p!=="shortRotation")if(p!=="scale"){this._firstPT=pt={_next:this._firstPT,t:m1,p:p,s:m1[p],c:m2[p]- m1[p],n:p,f:false,r:false,b:m1[p],e:m2[p],type:0};if(pt._next){pt._next._prev=pt;}
this._overwriteProps.push("raphael_"+ p);}}};});if(window._gsDefine){window._gsQueue.pop()();}